METplus: metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper Class Reference
metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper Class Reference
Takes tc-pairs data and regrids paired data to an n x m grid as specified in the config file.
Detailed Description
Takes tc-pairs data and regrids paired data to an n x m grid as specified in the config file.
Definition at line 21 of file extract_tiles_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def create_c_dict (self)
Create dictionary from config items to be used in the wrapper Allows developer to reference config items without having to know the type and consolidates config get calls so it is easier to see which config variables are used in the wrapper.
def regrid_data_plane_init (self)
create instance of RegridDataPlane wrapper, overriding default values for required config variables.
def run_at_time (self, input_dict)
Loops over loop strings and calls run_at_time_loop_string() to process data.
def run_at_time_loop_string (self, input_dict)
Read TCPairs track data into TCStat to filter the data.
def create_tiles_from_storm (self, storm_id, storm_lines, idx_dict)
Run RegridDataPlane to create a tile for forecast and observation data for each storm track point.
def get_grid (self, data_type, storm_data)
Call get_grid_info based on the data type, extracting the appropriate lat/lon data from the storm data.
def get_grid_info (self, lat, lon, data_type)
Create the grid specification string with the format: latlon Nx Ny lat_ll lon_ll delta_lat delta_lon used by the MET tool, regrid_data_plane.
Static Public Member Functions
def get_header_indices (header_line)
get indices of values from header line
def get_storm_data_from_track_line (idx_dict, storm_line)
Read line from storm track and populate a dictionary with the relevant items.
def set_time_info_from_storm_data (storm_id, storm_data)
Set time_info dictionary using init, lead, amodel, and storm ID that was extracted from the storm data.
Public Attributes
app_name
regrid_data_plane
Member Function Documentation
create_c_dict()
def metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.create_c_dict (self)
Create dictionary from config items to be used in the wrapper Allows developer to reference config items without having to know the type and consolidates config get calls so it is easier to see which config variables are used in the wrapper.
Returns
dictionary of values to use in wrapper
Definition at line 33 of file extract_tiles_wrapper.py.
create_tiles_from_storm()
def metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.create_tiles_from_storm (self, storm_id, storm_lines, idx_dict)
Run RegridDataPlane to create a tile for forecast and observation data for each storm track point.
Args:
Parameters
storm_id value from STORM_ID column to process
storm_lines Each line from tcst file for given storm id
idx_dict dictionary of indices for each header value
Definition at line 199 of file extract_tiles_wrapper.py.
Referenced by metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.run_at_time_loop_string().
get_grid()
def metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.get_grid (self, data_type, storm_data)
Call get_grid_info based on the data type, extracting the appropriate lat/lon data from the storm data.
Parameters
data_type type of data to process: must be FCST or OBS
storm_data dictionary containing information from the storm track line. Extract ALAT/ALON for FCST data and BLAT/BLON for OBS
Returns
grid info string or None if invalid data type is provided
Definition at line 303 of file extract_tiles_wrapper.py.
Referenced by metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.create_tiles_from_storm().
get_grid_info()
def metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.get_grid_info (self, lat, lon, data_type)
Create the grid specification string with the format: latlon Nx Ny lat_ll lon_ll delta_lat delta_lon used by the MET tool, regrid_data_plane.
Parameters
lat The latitude of the grid point
lon The longitude of the grid point
data_type FCST or OBS, used for log output only
Returns
the tile grid string for the input lat and lon
Definition at line 325 of file extract_tiles_wrapper.py.
Referenced by metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.get_grid().
get_header_indices()
def metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.get_header_indices (header_line) static
get indices of values from header line
Parameters
header_line first line in tcst file
Returns
dictionary where key is column name and value is the index of that column
Definition at line 240 of file extract_tiles_wrapper.py.
Referenced by metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.run_at_time_loop_string().
get_storm_data_from_track_line()
def metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.get_storm_data_from_track_line (idx_dict, storm_line) static
Read line from storm track and populate a dictionary with the relevant items.
Parameters
idx_dict dictionary where key is column name and value is the index of that column
storm_line line from tcst storm track file to parse
Returns
dictionary containing storm data where key is column name and value is the value extracted from the appropriate column of the line
Definition at line 264 of file extract_tiles_wrapper.py.
Referenced by metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.create_tiles_from_storm().
regrid_data_plane_init()
def metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.regrid_data_plane_init (self)
create instance of RegridDataPlane wrapper, overriding default values for required config variables.
Returns
instance of RegridDataPlaneWrapper
Definition at line 97 of file extract_tiles_wrapper.py.
run_at_time()
def metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.run_at_time (self, input_dict)
Loops over loop strings and calls run_at_time_loop_string() to process data.
Parameters
input_dict dictionary containing initialization time
Definition at line 132 of file extract_tiles_wrapper.py.
Referenced by metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), and metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times().
run_at_time_loop_string()
def metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.run_at_time_loop_string (self, input_dict)
Read TCPairs track data into TCStat to filter the data.
Using the resulting track data, run RegridDataPlane on the model data to create tiles centered on the storm.
Parameters
input_dict dictionary containing initialization time
Definition at line 148 of file extract_tiles_wrapper.py.
Referenced by metplus.wrappers.mtd_wrapper.MTDWrapper.run_at_time(), metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.run_at_time(), and metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_at_time().
set_time_info_from_storm_data()
def metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.set_time_info_from_storm_data (storm_id, storm_data) static
Set time_info dictionary using init, lead, amodel, and storm ID that was extracted from the storm data.
Parameters
storm_id ID of current storm
storm_data dictionary of data from a single storm line
Returns
time info dictionary with time, amodel, and storm_id set
Definition at line 282 of file extract_tiles_wrapper.py.
Referenced by metplus.wrappers.extract_tiles_wrapper.ExtractTilesWrapper.create_tiles_from_storm().
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/release-4.0.0-beta3/METplus/metplus/wrappers/extract_tiles_wrapper.py