METplus: wrappers.example_wrapper.ExampleWrapper Class Reference
wrappers.example_wrapper.ExampleWrapper Class Reference
Wrapper can be used as a base to develop a new wrapper.
Detailed Description
Wrapper can be used as a base to develop a new wrapper.
Definition at line 18 of file example_wrapper.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
def run_at_time (self, input_dict)
Do some processing for the current run time (init or valid) Args:
Public Attributes
app_name
Member Function Documentation
run_at_time()
def wrappers.example_wrapper.ExampleWrapper.run_at_time (self, input_dict)
Do some processing for the current run time (init or valid) Args:
Parameters
input_dict dictionary containing time information of current run generally contains 'now' (current) time and 'init' or 'valid' time
Definition at line 41 of file example_wrapper.py.
Referenced by wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_all_times(), and wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/example_wrapper.py