METplus: wrappers.series_analysis_wrapper.SeriesAnalysisWrapper Class Reference
wrappers.series_analysis_wrapper.SeriesAnalysisWrapper Class Reference
Detailed Description
Definition at line 26 of file series_analysis_wrapper.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
def clear (self)
def set_environment_variables (self, fcst_field, obs_field, time_info)
Set environment variables that will be read by the MET config file.
def get_command (self)
def run_all_times (self)
Get start time, loop over forecast leads and run SeriesAnalysis.
def run_at_time (self, time_info)
Process runtime and try to build command to run SeriesAnalysis Args:
def process_field_at_time (self, time_info, var_info)
def find_input_files (self, time_info, var_info)
def get_files_and_create_list (self, time_info, var_info, data_type)
def set_command_line_arguments (self, time_info)
def get_formatted_fields (self, var_info)
Public Attributes
app_name
app_path
isOK
Member Function Documentation
run_at_time()
def wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time (self, time_info)
Process runtime and try to build command to run SeriesAnalysis Args:
Parameters
time_info dictionary containing timing information
Definition at line 203 of file series_analysis_wrapper.py.
Referenced by wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_all_times(), and wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times().
set_environment_variables()
def wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.set_environment_variables (self, fcst_field, obs_field, time_info)
Set environment variables that will be read by the MET config file.
Reformat as needed. Print list of variables that were set and their values. Args:
Parameters
time_info dictionary containing timing info from current run
Definition at line 133 of file series_analysis_wrapper.py.
Referenced by wrappers.make_plots_wrapper.MakePlotsWrapper.create_c_dict(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper.run_at_time(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string(), wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once(), and wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/series_analysis_wrapper.py