METplus: wrappers.ensemble_stat_wrapper.EnsembleStatWrapper Class Reference
wrappers.ensemble_stat_wrapper.EnsembleStatWrapper Class Reference
Wraps the MET tool ensemble_stat to compare ensemble datasets.
Detailed Description
Wraps the MET tool ensemble_stat to compare ensemble datasets.
Definition at line 25 of file ensemble_stat_wrapper.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
Create a dictionary containing the values set in the config file that are required for running ensemble stat.
def run_at_time_all_fields (self, time_info)
Runs the MET application for a given time and forecast lead combination Args:
def get_all_field_info (self, var_list, data_type)
Get field info based on data type.
def find_model_members (self, time_info)
Finds the model member files to compare Args:
def set_environment_variables (self, fcst_field, obs_field, ens_field, time_info)
def process_fields (self, time_info, fcst_field, obs_field, ens_field=None)
Set and print environment variables, then build/run MET command Args:
def clear (self)
Unset class variables to prepare for next run time.
def get_command (self)
Builds the command to run the MET application string.
Public Attributes
app_name
app_path
isOK
param
point_obs_files
grid_obs_files
outdir
Member Function Documentation
create_c_dict()
def wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.create_c_dict (self)
Create a dictionary containing the values set in the config file that are required for running ensemble stat.
This will make it easier for unit testing.
Returns:
Returns
A dictionary of the ensemble stat values from the config file.
Definition at line 34 of file ensemble_stat_wrapper.py.
find_model_members()
def wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.find_model_members (self, time_info)
Finds the model member files to compare Args:
Parameters
time_info dictionary containing timing information string
Returns
Returns a list of the paths to the ensemble model files
Definition at line 251 of file ensemble_stat_wrapper.py.
Referenced by wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.run_at_time_all_fields().
get_command()
def wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.get_command (self)
Builds the command to run the MET application string.
Returns
Returns a MET command with arguments that you can run
Definition at line 392 of file ensemble_stat_wrapper.py.
Referenced by wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.build(), wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data(), wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.process_fields(), wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh(), wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), wrappers.gempak_to_cf_wrapper.GempakToCFWrapper.run_at_time_once(), wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_add_method(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_derive_method(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_subtract_method(), and wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_sum_method().
process_fields()
def wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.process_fields (self, time_info, fcst_field, obs_field, ens_field = None)
Set and print environment variables, then build/run MET command Args:
Parameters
time_info dictionary containing timing information
fcst_field field information formatted for MET config file
obs_field field information formatted for MET config file
Definition at line 357 of file ensemble_stat_wrapper.py.
Referenced by wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.run_at_time_all_fields().
run_at_time_all_fields()
def wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.run_at_time_all_fields (self, time_info)
Runs the MET application for a given time and forecast lead combination Args:
Parameters
time_info dictionary containing timing information
Definition at line 156 of file ensemble_stat_wrapper.py.
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/ensemble_stat_wrapper.py