METplus: wrappers.extract_tiles_wrapper.ExtractTilesWrapper Class Reference
wrappers.extract_tiles_wrapper.ExtractTilesWrapper Class Reference
Takes tc-pairs data and regrids paired data to an n x m grid as specified in the config file.
Detailed Description
Takes tc-pairs data and regrids paired data to an n x m grid as specified in the config file.
Definition at line 30 of file extract_tiles_wrapper.py.
Public Member Functions
def __init__ (self, config)
def run_at_time (self, input_dict)
Loops over loop strings and calls run_at_time_loop_string() to process data Args: input_dict: Time dictionary Returns: None.
def run_at_time_loop_string (self, input_dict)
Get TC-paris data then regrid tiles centered on the storm.
def tc_files_exist (self)
def do_filtering (self, cur_init, filter_name)
def create_results_files (self, sorted_storm_ids, cur_init, filter_name, tmp_dir)
Public Attributes
app_name
tc_pairs_dir
overwrite_flag
addl_filter_opts
filtered_out_dir
tc_stat_exe
Member Function Documentation
create_results_files()
def wrappers.extract_tiles_wrapper.ExtractTilesWrapper.create_results_files (self, sorted_storm_ids, cur_init, filter_name, tmp_dir)
Create the tmp files that contain filtered results- one tmp file per storm, then
    invoke retrieve_and_regrid to create the final output as netCDF forecast and analysis (obs)
    files.
    Args:
@param sorted_storm_ids:
@param cur_init: The current init time of interest
@param filter_name: The full file name of the filter file generated by tc stat
@param tmp_dir: The location of the tmp directory where these tmp files will be saved
    Return:
     0 if successful in creating the tmp files (one per storm) in the tmp_dir
Definition at line 187 of file extract_tiles_wrapper.py.
Referenced by wrappers.extract_tiles_wrapper.ExtractTilesWrapper.run_at_time_loop_string().
do_filtering()
def wrappers.extract_tiles_wrapper.ExtractTilesWrapper.do_filtering (self, cur_init, filter_name)
run TC_STAT because the filter output file hasn't yet been created
    by the MET tc stat tool.
    Args:
@param cur_init:  The current init time of interest
@param filter_name: The full filename of the file that will contain filtered results generated
                    by the MET tool tc stat.
    Return:
0 if MET tc stat tool completed successfully (which will
create a filter_name file (which was defined/created in run_at_time()
in the output directory).
Definition at line 156 of file extract_tiles_wrapper.py.
Referenced by wrappers.extract_tiles_wrapper.ExtractTilesWrapper.run_at_time_loop_string().
run_at_time_loop_string()
def wrappers.extract_tiles_wrapper.ExtractTilesWrapper.run_at_time_loop_string (self, input_dict)
Get TC-paris data then regrid tiles centered on the storm.
Get TC-pairs track data and GFS model data, do any necessary processing then regrid the forecast and analysis files to a 30 x 30 degree tile centered on the storm. Args: input_dict: Time dictionary Returns:
None: invokes regrid_data_plane to create a netCDF file from two
extratropical storm track files.
Definition at line 69 of file extract_tiles_wrapper.py.
Referenced by wrappers.extract_tiles_wrapper.ExtractTilesWrapper.run_at_time(), wrappers.mtd_wrapper.MTDWrapper.run_at_time(), and wrappers.tc_pairs_wrapper.TCPairsWrapper.run_at_time().
tc_files_exist()
def wrappers.extract_tiles_wrapper.ExtractTilesWrapper.tc_files_exist (self)
Check that there are tc_pairs data files (.tcst) which are needed as input
    to the extract tiles wrapper
    Args:
    Return:
True if .tcst files exist, False otherwise
Definition at line 138 of file extract_tiles_wrapper.py.
Referenced by wrappers.extract_tiles_wrapper.ExtractTilesWrapper.run_at_time_loop_string().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/extract_tiles_wrapper.py