METplus: metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper Class Reference
metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper Class Reference
Performs series analysis with filtering options.
Detailed Description
Performs series analysis with filtering options.
Definition at line 33 of file series_analysis_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def create_c_dict (self)
Populate c_dict dictionary with values from METplusConfig.
def plot_data_plane_init (self)
Set values to allow successful initialization of PlotDataPlane wrapper.
def clear (self)
Call parent's clear function and clear additional values.
def run_all_times (self)
Process all run times defined for this wrapper.
def run_once_per_lead (self, custom)
Run once per forecast lead.
def run_at_time_once (self, time_info, lead_group=None)
Attempt to build series_analysis command for run time.
def get_storm_list (self, time_info)
Find the .tcst filter file for the current run time and get the list of storm IDs that are found in the file.
def get_files_from_time (self, time_info)
Create dictionary containing time information (key time_info) and any relevant files for that runtime.
def find_input_files (self, time_info, data_type)
Loop over list of input templates and find files for each.
def subset_input_files (self, time_info)
Obtain a subset of input files from the c_dict ALL_FILES based on the time information for the current run.
def compare_time_info (self, runtime, filetime)
Call parents implementation then if the current run time and file time may potentially still not match, use storm_id to check.
def create_ascii_storm_files_list (self, time_info, storm_id, lead_group)
Creates the list of ASCII files that contain the storm id and init times.
def check_python_embedding (self)
Check if any of the field names contain a Python embedding script.
def get_output_dir (self, time_info, storm_id, label)
Determine directory that will contain output data from the OUTPUT_DIR and OUTPUT_TEMPLATE.
def build_and_run_series_request (self, time_info, fcst_path, obs_path)
Build up the -obs, -fcst, -out necessary for running the series_analysis MET tool, then invoke series_analysis.
def set_environment_variables (self, time_info, fcst_field, obs_field)
Set the env variables based on settings in the METplus config files.
def set_command_line_arguments (self, time_info)
Set arguments that will be passed into the MET command.
def get_command (self)
Build command to run.
def generate_plots (self, fcst_path, time_info, storm_id)
Generate the plots from the series_analysis output.
def generate_animations (self)
Use ImageMagick convert to create an animated gif from the png images generated from the current run.
def get_fcst_file_info (self, fcst_path)
Get the number of all the gridded forecast n x m tile files.
def get_formatted_fields (self, var_info)
Get forecast and observation field information for var_info and format it so it can be passed into the MET config file.
Static Public Member Functions
def get_ascii_filename (data_type, storm_id, leads=None)
Build filename for ASCII file list file.
def get_netcdf_min_max (filepath, variable_name)
Determine the min and max for all lead times for each statistic and variable pairing.
Public Attributes
app_name
app_path
plot_data_plane
Member Function Documentation
build_and_run_series_request()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.build_and_run_series_request (self, time_info, fcst_path, obs_path)
Build up the -obs, -fcst, -out necessary for running the series_analysis MET tool, then invoke series_analysis.
Parameters
time_info dictionary containing time information for current run
storm_id storm ID to process
Returns
True if all runs succeeded, False if there was a problem with any of the runs
Definition at line 655 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time_once().
check_python_embedding()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.check_python_embedding (self)
Check if any of the field names contain a Python embedding script.
See CommandBuilder.check_for_python_embedding for more info.
Returns
False if something is not configured correctly or True
Definition at line 565 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.create_ascii_storm_files_list().
compare_time_info()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.compare_time_info (self, runtime, filetime)
Call parents implementation then if the current run time and file time may potentially still not match, use storm_id to check.
Parameters
runtime dictionary containing time information for current runtime
filetime dictionary containing time information for file that is being evaluated
Returns
True if the file should be processed in the current run or False if not
Definition at line 473 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.grid_diag_wrapper.GridDiagWrapper.subset_input_files(), and metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.subset_input_files().
create_ascii_storm_files_list()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.create_ascii_storm_files_list (self, time_info, storm_id, lead_group)
Creates the list of ASCII files that contain the storm id and init times.
The list is used to create an ASCII file which will be used as the option to the -obs or -fcst flag to the MET series_analysis tool.
Parameters
time_info dictionary containing time information
storm_id storm ID to process
lead_group dictionary where key is label and value is a list of forecast leads to process. If no label was defined, the key will match the format "NoLabel_<n>" and if no lead groups are defined, the dictionary should be replaced with None
Definition at line 493 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time_once().
find_input_files()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.find_input_files (self, time_info, data_type)
Loop over list of input templates and find files for each.
Parameters
time_info time dictionary to use for string substitution
Returns
Input file list if all files were found, None if not.
Definition at line 441 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.get_files_from_time(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), and metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once().
generate_plots()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.generate_plots (self, fcst_path, time_info, storm_id)
Generate the plots from the series_analysis output.
Parameters
time_info dictionary containing time information
storm_id storm ID to process
Definition at line 794 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time_once().
get_ascii_filename()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.get_ascii_filename (data_type, storm_id, leads = None) static
Build filename for ASCII file list file.
Parameters
data_type FCST, OBS, or BOTH
storm_id current storm ID or wildcard character
leads list of forecast leads to use add the forecast hour string to the filename or the minimum and maximum forecast hour strings if there are more than one lead
Returns
string containing filename to use
Definition at line 584 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.create_ascii_storm_files_list().
get_command()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.get_command (self)
Build command to run.
Returns
string of the command that will be called
Definition at line 771 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.build(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), and metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once().
get_fcst_file_info()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.get_fcst_file_info (self, fcst_path)
Get the number of all the gridded forecast n x m tile files.
Determine the filename of the first and last files. This information is used to create the title value to the -title opt in plot_data_plane.
Parameters
fcst_path path to forecast ascii list file to process
Returns
num, beg, end: A tuple representing the number of forecast tile files, and the first and last file. If info cannot be parsed, return (None, None, None)
Definition at line 898 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.build_and_run_series_request(), and metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.generate_plots().
get_files_from_time()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.get_files_from_time (self, time_info)
Create dictionary containing time information (key time_info) and any relevant files for that runtime.
The parent implementation of this function creates a dictionary and adds the time_info to it. This wrapper gets all files for the current runtime and adds it to the dictionary with keys 'fcst' and 'obs'
Parameters
time_info dictionary containing time information
Returns
dictionary containing time_info dict and any relevant files with a key representing a description of that file
Definition at line 405 of file series_analysis_wrapper.py.
get_formatted_fields()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.get_formatted_fields (self, var_info)
Get forecast and observation field information for var_info and format it so it can be passed into the MET config file.
Parameters
var_info dictionary containing info to format
Returns
tuple containing strings of the formatted forecast and observation information or None, None if something went wrong
Definition at line 972 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.build_and_run_series_request().
get_netcdf_min_max()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.get_netcdf_min_max (filepath, variable_name) static
Determine the min and max for all lead times for each statistic and variable pairing.
Parameters
filepath NetCDF file to inspect
variable_name name of variable to read
Returns
tuple containing the minimum and maximum values or None, None if something went wrong
Definition at line 955 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.generate_plots().
get_output_dir()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.get_output_dir (self, time_info, storm_id, label)
Determine directory that will contain output data from the OUTPUT_DIR and OUTPUT_TEMPLATE.
This will include any subdirectories specified in the filename template.
Parameters
time_info dictionary containing time information for current run
storm_id storm ID to process
label label defined for forecast lead groups to identify them
Returns
path to output directory with filename templates substituted with the information for the current run
Definition at line 627 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.create_ascii_storm_files_list().
get_storm_list()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.get_storm_list (self, time_info)
Find the .tcst filter file for the current run time and get the list of storm IDs that are found in the file.
Parameters
time_info dictionary containing time information
Returns
A list of all the storms ids that correspond to the current init time or None if filter file does not exist
Definition at line 374 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.get_files_from_time(), and metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time_once().
plot_data_plane_init()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.plot_data_plane_init (self)
Set values to allow successful initialization of PlotDataPlane wrapper.
Returns
instance of PlotDataPlaneWrapper
Definition at line 243 of file series_analysis_wrapper.py.
run_at_time_once()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time_once (self, time_info, lead_group = None)
Attempt to build series_analysis command for run time.
Parameters
time_info dictionary containing time information
lead_group (optional) dictionary where key is label and value is a list of forecast leads to process.
Returns
True on success, False otherwise
Definition at line 328 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.generate_plots(), metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.run_all_times_custom(), metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.run_at_time(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time(), metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time(), and metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_once_per_lead().
run_once_per_lead()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_once_per_lead (self, custom)
Run once per forecast lead.
Parameters
value of current CUSTOM_LOOP_LIST iteration
Returns
True if all runs were successful, False otherwise
Definition at line 279 of file series_analysis_wrapper.py.
set_command_line_arguments()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.set_command_line_arguments (self, time_info)
Set arguments that will be passed into the MET command.
Parameters
time_info dictionary containing time information
Definition at line 756 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.build_and_run_series_request(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), and metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once().
set_environment_variables()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.set_environment_variables (self, time_info, fcst_field, obs_field)
Set the env variables based on settings in the METplus config files.
Parameters
time_info dictionary containing time information
fcst_field formatted forecast field information
obs_field formatted observation field information
Definition at line 703 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.build_and_run_series_request(), metplus.wrappers.make_plots_wrapper.MakePlotsWrapper.create_c_dict(), metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), metplus.wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper.run_at_time(), metplus.wrappers.tc_stat_wrapper.TCStatWrapper.run_at_time(), metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string(), metplus.wrappers.user_script_wrapper.UserScriptWrapper.run_at_time_once(), metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time_once(), metplus.wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once(), and metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
subset_input_files()
def metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.subset_input_files (self, time_info)
Obtain a subset of input files from the c_dict ALL_FILES based on the time information for the current run.
Parameters
time_info dictionary containing time information
Returns
the path to a ascii file containing the list of files or None if could not find any files
Definition at line 452 of file series_analysis_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.create_ascii_storm_files_list().
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/release-4.0.0-beta3/METplus/metplus/wrappers/series_analysis_wrapper.py