METplus: wrappers.mtd_wrapper.MTDWrapper Class Reference
wrappers.mtd_wrapper.MTDWrapper Class Reference
Detailed Description
Definition at line 21 of file mtd_wrapper.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
def run_at_time (self, input_dict)
Runs the MET application for a given run time.
def run_at_time_loop_string (self, input_dict)
Runs the MET application for a given run time.
def run_single_mode (self, input_dict, var_info)
def process_fields_one_thresh (self, time_info, var_info, model_path, obs_path)
For each threshold, set up environment variables and run mode Args:
def set_fcst_file (self, fcst_file)
def set_obs_file (self, obs_file)
def clear (self)
def set_environment_variables (self, fcst_field, obs_field, var_info, time_info)
def get_command (self)
Builds the command to run the MET application string.
Public Attributes
app_name
app_path
fcst_file
obs_file
param
Member Function Documentation
get_command()
def wrappers.mtd_wrapper.MTDWrapper.get_command (self)
Builds the command to run the MET application string.
Returns
Returns a MET command with arguments that you can run
Definition at line 430 of file mtd_wrapper.py.
Referenced by wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.build(), wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data(), wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh(), wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_add_method(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_derive_method(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_subtract_method(), and wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_sum_method().
process_fields_one_thresh()
def wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh (self, time_info, var_info, model_path, obs_path)
For each threshold, set up environment variables and run mode Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
model_path forecast file list path
obs_path observation file list path
Definition at line 274 of file mtd_wrapper.py.
Referenced by wrappers.mtd_wrapper.MTDWrapper.run_at_time_loop_string().
run_at_time()
def wrappers.mtd_wrapper.MTDWrapper.run_at_time (self, input_dict)
Runs the MET application for a given run time.
This function loops over the list of user-defined strings and runs the application for each. Overrides run_at_time in compare_gridded_wrapper.py Args:
Parameters
input_dict dictionary containing timing information
Definition at line 124 of file mtd_wrapper.py.
Referenced by wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_all_times(), and wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times().
run_at_time_loop_string()
def wrappers.mtd_wrapper.MTDWrapper.run_at_time_loop_string (self, input_dict)
Runs the MET application for a given run time.
This function loops over the list of forecast leads and runs the application for each. Overrides run_at_time in compare_gridded_wrapper.py Args:
Parameters
input_dict dictionary containing timing information
Definition at line 143 of file mtd_wrapper.py.
Referenced by wrappers.mtd_wrapper.MTDWrapper.run_at_time(), and wrappers.tc_pairs_wrapper.TCPairsWrapper.run_at_time().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/mtd_wrapper.py