METplus: wrappers.tc_stat_wrapper.TCStatWrapper Class Reference
wrappers.tc_stat_wrapper.TCStatWrapper Class Reference
Wrapper for the MET tool, tc_stat, which is used to filter tropical cyclone pair data.
Detailed Description
Wrapper for the MET tool, tc_stat, which is used to filter tropical cyclone pair data.
Definition at line 33 of file tc_stat_wrapper.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
Read in and store all the values from the config file.
def run_all_times (self)
Builds the call to the MET tool TC-STAT for all requested initialization times (init or valid).
def set_envs (self)
Set the env variables based on settings in the METplus config files.
def config_lists_ok (self)
Verify that the length of the name and val lists in the MET tc-stat config file are of equal length, if not, log an error message and exit.
def build_tc_stat (self, tc_stat_output_dir, cur_init, tc_input_list, filter_opts)
This is called from extract_tiles_wrapper and from any other wrapper to provide additional filtering WITHOUT the need for a tc_stat MET config file.
Public Attributes
app_name
by_config
tc_exe
Member Function Documentation
build_tc_stat()
def wrappers.tc_stat_wrapper.TCStatWrapper.build_tc_stat (self, tc_stat_output_dir, cur_init, tc_input_list, filter_opts)
This is called from extract_tiles_wrapper and from any other wrapper to provide additional filtering WITHOUT the need for a tc_stat MET config file.
Creates the call to MET tool TC-STAT to subset tc-pairs output based on the criteria specified in the feature relative use case parameter/config file.
Args:
Parameters
tc_stat_output_dir The output directory where filtered results are saved.
cur_init The initialization time
tc_input_list The "list" of input data (the files containing the tc pair data to be filtered) in a string
filter_opts The list of filter options to apply
Returns: None: if no error, then invoke MET tool TC-STAT and subsets tc-pairs data, creating a filter.tcst file.
Raises CalledProcessError
Definition at line 764 of file tc_stat_wrapper.py.
Referenced by wrappers.tc_stat_wrapper.TCStatWrapper.config_lists_ok().
config_lists_ok()
def wrappers.tc_stat_wrapper.TCStatWrapper.config_lists_ok (self)
Verify that the length of the name and val lists in the MET tc-stat config file are of equal length, if not, log an error message and exit.
As soon as a length mismatch is encountered, return False.
Args:
Returns: True: if all corresponding <>_NAME and <>_VAL lists have the same length False: if any name/val list length mismatch is encountered
Definition at line 694 of file tc_stat_wrapper.py.
Referenced by wrappers.tc_stat_wrapper.TCStatWrapper.run_all_times().
create_c_dict()
def wrappers.tc_stat_wrapper.TCStatWrapper.create_c_dict (self)
Read in and store all the values from the config file.
This will make it easier to reassign values while unit testing and make it easier when retrieving these values, especially when they are needed multiple times by different methods.
Args:
Returns: tc_stat_dict - a dictionary of the key-value representation of options set in the config file.
Definition at line 50 of file tc_stat_wrapper.py.
run_all_times()
def wrappers.tc_stat_wrapper.TCStatWrapper.run_all_times (self)
Builds the call to the MET tool TC-STAT for all requested initialization times (init or valid).
Called from master_metplus
Args:
Returns: 0 if successfully runs MET tc_stat tool. 1 otherwise
Definition at line 243 of file tc_stat_wrapper.py.
set_envs()
def wrappers.tc_stat_wrapper.TCStatWrapper.set_envs (self)
Set the env variables based on settings in the METplus config files.
This is only necessary when running MET tc_stat via the config file.
Args:
Returns: 0 - if successfully sets env variable
Definition at line 315 of file tc_stat_wrapper.py.
Referenced by wrappers.tc_stat_wrapper.TCStatWrapper.run_all_times().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/tc_stat_wrapper.py