METplus: metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper Class Reference
metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper Class Reference
Performs series analysis based on init time by first performing any additional filtering via the wrapper to the MET tool tc_stat, tc_stat_wrapper.
Detailed Description
Performs series analysis based on init time by first performing any additional filtering via the wrapper to the MET tool tc_stat, tc_stat_wrapper.
Next, the arguments to run the MET tool series_analysis is done
Definition at line 24 of file series_by_init_wrapper.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
def run_all_times (self)
Invoke the series analysis script based on the init time in the format YYYYMMDD_hh.
def apply_series_filters (self, tile_dir, init_times, series_output_dir, filter_opts, staging_dir)
Apply filter options, as specified in the param/config file.
def is_netcdf_created (self)
Check for the presence of NetCDF files in the series_analysis_init directory.
def get_fcst_file_info (self, dir_to_search, cur_init, cur_storm)
Get the number of all the gridded forecast n x m tile files for a given storm id and init time (that were created by extract_tiles).
def get_ascii_storm_files_list (self, tile_dir)
Creates the list of ASCII files that contain the storm id and init times.
def build_and_run_series_request (self, sorted_filter_init, tile_dir)
Build up the -obs, -fcst, -out necessary for running the series_analysis MET tool, then invoke series_analysis.
def create_obs_fcst_arg (self, param_arg, ascii_file_base, cur_storm, cur_init)
Create the argument to the -obs or -fcst flag to the MET tool, series_analysis.
def create_out_arg (self, cur_storm, cur_init, name, level)
Create/build the -out portion of the series_analysis command and creates the output directory.
def clear (self)
def add_input_file (self, filename, type_id)
def get_command (self)
def generate_plots (self, sorted_filter_init, tile_dir)
Generate the plots from the series_analysis output.
def get_storms_for_init (self, cur_init, out_dir_base)
Retrieve all the filter files which have the .tcst extension.
def create_fcst_anly_to_ascii_file (self, fcst_anly_grid_files, cur_init, cur_storm, fcst_anly_filename_base)
Create ASCII file for either the FCST or ANLY files that are aggregated based on init time and storm id.
Public Attributes
app_path
app_name
stat_list
extract_tiles_dir
series_out_dir
series_filtered_out_dir
filter_opts
fcst_ascii_file_prefix
anly_ascii_file_prefix
convert_exe
isOK
sbi_plotting_out_dir
inaddons
infiles
outdir
outfile
args
param
Member Function Documentation
apply_series_filters()
def metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.apply_series_filters (self, tile_dir, init_times, series_output_dir, filter_opts, staging_dir)
Apply filter options, as specified in the param/config file.
Args:
Parameters
tile_dir Directory where input data files reside. e.g. data which we will be applying our filter criteria.
init_times List of init times that define the input data.
series_output_dir The directory where the filter results will be stored.
filter_opts The filter options to apply
staging_dir The staging directory where intermediate files are saved. Returns: None
Definition at line 207 of file series_by_init_wrapper.py.
Referenced by metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.filter_with_tc_stat(), and metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.run_all_times().
build_and_run_series_request()
def metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.build_and_run_series_request (self, sorted_filter_init, tile_dir)
Build up the -obs, -fcst, -out necessary for running the series_analysis MET tool, then invoke series_analysis.
Args:
Parameters
sorted_filter_init A list of the sorted directories corresponding to the init times that are the result of filtering. If filtering produced no results, this is the list of files created from running extract_tiles.
tile_dir The directory where the input resides. Returns:
Definition at line 482 of file series_by_init_wrapper.py.
Referenced by metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.run_all_times().
create_fcst_anly_to_ascii_file()
def metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.create_fcst_anly_to_ascii_file (self, fcst_anly_grid_files, cur_init, cur_storm, fcst_anly_filename_base)
Create ASCII file for either the FCST or ANLY files that are aggregated based on init time and storm id.
Args: fcst_anly_grid_files: A list of the FCST or ANLY gridded files under consideration.
cur_init: The initialization time of interest
cur_storm: The storm id of interest
fcst_anly_filename_base: The base name of the ASCII file (either ANLY_ASCII_FILES_ or FCST_ASCII_FILES_ which will be appended with the storm id.
Returns: None: Creates an ASCII file containing a list of either FCST or ANLY files based on init time and storm id.
Definition at line 819 of file series_by_init_wrapper.py.
Referenced by metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.get_ascii_storm_files_list(), and metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.get_storms_for_init().
create_obs_fcst_arg()
def metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.create_obs_fcst_arg (self, param_arg, ascii_file_base, cur_storm, cur_init)
Create the argument to the -obs or -fcst flag to the MET tool, series_analysis.
Args:
Parameters
param_arg '-obs' for the -obs argument to series_analysis, or '-fcst' for the -fcst argument to series_analysis.
ascii_file_base The base name of the obs or fcst ASCII file that contains a list of the full filepath to the input files.
cur_storm The storm of interest.
cur_init The initialization time of interest.
Returns:
Definition at line 540 of file series_by_init_wrapper.py.
Referenced by metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.build_and_run_series_request().
create_out_arg()
def metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.create_out_arg (self, cur_storm, cur_init, name, level)
Create/build the -out portion of the series_analysis command and creates the output directory.
Args:
Parameters
cur_storm The storm of interest.
cur_init The initialization time of interest.
name The variable name of interest.
level The level of interest.
Returns:
Definition at line 574 of file series_by_init_wrapper.py.
Referenced by metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.build_and_run_series_request().
generate_plots()
def metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.generate_plots (self, sorted_filter_init, tile_dir)
Generate the plots from the series_analysis output.
Args:
Parameters
sorted_filter_init A list of the sorted directories corresponding to the init times (that are the result of filtering). If filtering produced no results, this is the list of files created from running extract_tiles.
tile_dir The directory where input data resides. Returns:
Definition at line 651 of file series_by_init_wrapper.py.
Referenced by metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.run_all_times(), and metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times().
get_ascii_storm_files_list()
def metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.get_ascii_storm_files_list (self, tile_dir)
Creates the list of ASCII files that contain the storm id and init times.
The list is used to create an ASCII file which will be used as the option to the -obs or -fcst flag to the MET series_analysis tool. Args:
Parameters
tile_dir The directory where input files reside. Returns: sorted_filter_init: A list of the sorted directories corresponding to the init times after filtering has been applied. If filtering produced no results, this is the list of files created from running extract_tiles.
Definition at line 412 of file series_by_init_wrapper.py.
Referenced by metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.run_all_times().
get_fcst_file_info()
def metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.get_fcst_file_info (self, dir_to_search, cur_init, cur_storm)
Get the number of all the gridded forecast n x m tile files for a given storm id and init time (that were created by extract_tiles).
Determine the filename of the first and last files. This information is used to create the title value to the -title opt in plot_data_plane.
Args:
Parameters
dir_to_search The directory of the gridded files of interest.
cur_init The init time of interest.
cur_storm The storm id of interest.
Returns: num, beg, end: A tuple representing the number of forecast tile files, and the first and last file.
sys.exit(1) otherwise
Definition at line 340 of file series_by_init_wrapper.py.
Referenced by metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.generate_plots().
get_storms_for_init()
def metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.get_storms_for_init (self, cur_init, out_dir_base)
Retrieve all the filter files which have the .tcst extension.
Inside each file, extract the STORM_ID and append to the list, if the storm_list directory exists.
Args:
Parameters
cur_init the init time
out_dir_base The directory where one should start searching for the filter file(s)
those with a .tcst file extension.
Returns: storm_list: A list of all the storms ids that correspond to this init time and actually has a directory in the init dir (additional filtering in a previous step may result in missing storm ids even though they are in the filter.tcst file)
Definition at line 778 of file series_by_init_wrapper.py.
Referenced by metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.build_and_run_series_request(), metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.generate_plots(), and metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.get_ascii_storm_files_list().
is_netcdf_created()
def metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.is_netcdf_created (self)
Check for the presence of NetCDF files in the series_analysis_init directory.
Returns: is_created True if NetCDF files were found in the series_analysis_init/YYYYMMDD_hh/storm sub-directories, False otherwise.
Definition at line 307 of file series_by_init_wrapper.py.
Referenced by metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.run_all_times().
run_all_times()
def metplus.wrappers.series_by_init_wrapper.SeriesByInitWrapper.run_all_times (self)
Invoke the series analysis script based on the init time in the format YYYYMMDD_hh.
Args:
Returns: None: Creates graphical plots of storm tracks
Definition at line 68 of file series_by_init_wrapper.py.
The documentation for this class was generated from the following file:
/d1/personal/mccabe/release/METplus/metplus/wrappers/series_by_init_wrapper.py