METplus: metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper Class Reference
metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper Class Reference
Wraps the MET tool, tc_pairs to parse and match ATCF_by_pairs adeck and bdeck files.
Detailed Description
Wraps the MET tool, tc_pairs to parse and match ATCF_by_pairs adeck and bdeck files.
Pre-processes extra tropical cyclone data.
Definition at line 38 of file tc_pairs_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def create_c_dict (self)
Create a dictionary containing all the values set in the config file.
def run_all_times (self)
Build up the command to invoke the MET tool tc_pairs.
def run_at_time (self, input_dict)
Create the arguments to run MET tc_pairs Args: input_dict dictionary containing init or valid time Returns:
def run_at_time_loop_string (self, input_dict)
Create the arguments to run MET tc_pairs Args: input_dict dictionary containing init or valid time Returns:
def set_environment_variables (self, time_info)
Set up all the environment variables that are assigned in the METplus config file which are to be used by the MET TC-pairs config file.
def process_data (self, basin, cyclone, model_list, time_info)
Find requested files and run tc_pairs Args:
def find_deck_files (self, deck, basin, cyclone, model_list, time_info)
Find ADECK or EDECK files that correspond to the BDECk file found Args:
def reformat_files (self, file_list, deck_type, time_info)
Reformat track data to match expected ATCF format Args:
def get_command (self)
Over-ride CommandBuilder's get_command because unlike other MET tools, tc_pairs handles input files differently- namely, through flags -adeck and -bdeck and doesn't require an output file, as there is a default.
def read_modify_write_file (self, in_csvfile, storm_month, missing_values, out_csvfile)
Reads, modifies and writes file Args:
Public Attributes
app_name
app_path
adeck
bdeck
edeck
outdir
outfile
Member Function Documentation
create_c_dict()
def metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.create_c_dict (self)
Create a dictionary containing all the values set in the config file.
This will make it easier for unit testing.
Args:
Returns: c_dict - A dictionary of the values from the config file
Definition at line 54 of file tc_pairs_wrapper.py.
find_deck_files()
def metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.find_deck_files (self, deck, basin, cyclone, model_list, time_info)
Find ADECK or EDECK files that correspond to the BDECk file found Args:
Parameters
deck type of deck (A or E)
basin region of storm from config
cyclone ID number of cyclone from config
model_list list of models that be available
time_info object containing timing information to process
Definition at line 606 of file tc_pairs_wrapper.py.
Referenced by metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data().
get_command()
def metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.get_command (self)
Over-ride CommandBuilder's get_command because unlike other MET tools, tc_pairs handles input files differently- namely, through flags -adeck and -bdeck and doesn't require an output file, as there is a default.
Build command to run from arguments
Definition at line 678 of file tc_pairs_wrapper.py.
Referenced by metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.build(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), and metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once().
process_data()
def metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data (self, basin, cyclone, model_list, time_info)
Find requested files and run tc_pairs Args:
Parameters
basin region of storm from config
cyclone ID number of cyclone from config
model_list list of models that be available
time_info object containing timing information to process
Definition at line 465 of file tc_pairs_wrapper.py.
Referenced by metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string().
read_modify_write_file()
def metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.read_modify_write_file (self, in_csvfile, storm_month, missing_values, out_csvfile)
Reads, modifies and writes file Args:
Parameters
in_csvfile input csv file that is being parsed
storm_month The storm month
missing_values a tuple where (MISSING_VAL_TO_REPLACE, MISSING_VAL)
out_csvfile the output csv file
logger the log where logging is directed
Definition at line 725 of file tc_pairs_wrapper.py.
Referenced by metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.get_command(), and metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.reformat_files().
reformat_files()
def metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.reformat_files (self, file_list, deck_type, time_info)
Reformat track data to match expected ATCF format Args:
Parameters
file_list list of files to reformat
deck_type type of deck (A or E)
time_info object with timing information to get storm month Returns: list of output files that are in ATCF format
Definition at line 645 of file tc_pairs_wrapper.py.
Referenced by metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data().
set_environment_variables()
def metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.set_environment_variables (self, time_info)
Set up all the environment variables that are assigned in the METplus config file which are to be used by the MET TC-pairs config file.
Args: nothing - retrieves necessary MET+ config values via class attributes
Returns: nothing - sets the environment variables
Definition at line 306 of file tc_pairs_wrapper.py.
Referenced by metplus.wrappers.make_plots_wrapper.MakePlotsWrapper.create_c_dict(), metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), metplus.wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper.run_at_time(), metplus.wrappers.tc_stat_wrapper.TCStatWrapper.run_at_time(), metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string(), metplus.wrappers.user_script_wrapper.UserScriptWrapper.run_at_time_once(), metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time_once(), metplus.wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once(), and metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/release-4.0.0-beta3/METplus/metplus/wrappers/tc_pairs_wrapper.py