METplus: wrappers.reformat_gridded_wrapper.ReformatGriddedWrapper Class Reference
wrappers.reformat_gridded_wrapper.ReformatGriddedWrapper Class Reference
Common functionality to wrap similar MET applications that reformat gridded data.
Detailed Description
Common functionality to wrap similar MET applications that reformat gridded data.
Definition at line 29 of file reformat_gridded_wrapper.py.
Public Member Functions
def __init__ (self, config)
def run_at_time_once (self, time_info, var_list, data_type)
To be implemented by child class.
def run_at_time (self, input_dict)
Runs the MET application for a given run time.
Member Function Documentation
run_at_time()
def wrappers.reformat_gridded_wrapper.ReformatGriddedWrapper.run_at_time (self, input_dict)
Runs the MET application for a given run time.
Processing forecast or observation data is determined by conf variables. This function loops over the list of forecast leads and runs the application for each. Args:
Parameters
init_time initialization time to run. -1 if not set
valid_time valid time to run. -1 if not set
Definition at line 44 of file reformat_gridded_wrapper.py.
Referenced by wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_all_times(), and wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/reformat_gridded_wrapper.py