METplus: metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper Class Reference
metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper Class Reference
Detailed Description
Definition at line 26 of file gen_vx_mask_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def create_c_dict (self)
def get_command (self)
def run_at_time (self, input_dict)
Runs the MET application for a given run time.
def run_at_time_all (self, time_info)
Loop over list of mask templates and call GenVxMask for each, adding the corresponding command line arguments for each call Args:
def find_input_files (self, time_info, temp_file)
Handle setting of input file list.
Public Attributes
app_name
app_path
isOK
args
Member Function Documentation
find_input_files()
def metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.find_input_files (self, time_info, temp_file)
Handle setting of input file list.
Args:
Parameters
time_info time dictionary for current runtime
temp_file path to temporary file used for previous run or empty string on first iteration
Returns
True if successfully found all inputs, False if not
Definition at line 203 of file gen_vx_mask_wrapper.py.
Referenced by metplus.wrappers.grid_diag_wrapper.GridDiagWrapper.get_files_from_time(), metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.get_files_from_time(), metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time_once(), metplus.wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), metplus.wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), and metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once().
run_at_time()
def metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time (self, input_dict)
Runs the MET application for a given run time.
This function loops over the list of forecast leads and runs the application for each. Args:
Parameters
input_dict dictionary containing timing information
Returns
None
Definition at line 131 of file gen_vx_mask_wrapper.py.
Referenced by metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), and metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times().
run_at_time_all()
def metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all (self, time_info)
Loop over list of mask templates and call GenVxMask for each, adding the corresponding command line arguments for each call Args:
Parameters
time_info time dictionary for current runtime
Returns
None
Definition at line 158 of file gen_vx_mask_wrapper.py.
Referenced by metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time().
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/METplus/metplus/wrappers/gen_vx_mask_wrapper.py