METplus: metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper Class Reference
metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper Class Reference
Detailed Description
Definition at line 27 of file runtime_freq_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def create_c_dict (self)
def run_all_times (self)
def run_all_times_custom (self, custom)
Run the wrapper based on the time frequency specified.
def run_once (self, custom)
def run_once_per_init_or_valid (self, custom)
def run_once_per_lead (self, custom)
def run_at_time (self, input_dict)
Runs the command for a given run time.
def get_all_files (self, custom=None)
Get all files that can be processed with the app.
def get_files_from_time (self, time_info)
Create dictionary containing time information (key time_info) and any relevant files for that runtime.
def compare_time_info (self, runtime, filetime)
Compare current runtime dictionary to current file time dictionary If runtime value for init, valid, or lead is not a wildcard and it doesn't match the file's time value, return False.
Public Attributes
all_commands
Static Public Attributes
list FREQ_OPTIONS
Member Function Documentation
compare_time_info()
def metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.compare_time_info (self, runtime, filetime)
Compare current runtime dictionary to current file time dictionary If runtime value for init, valid, or lead is not a wildcard and it doesn't match the file's time value, return False.
Otherwise return True.
Parameters
runtime dictionary containing time info for current runtime
filetime dictionary containing time info for current file
Returns
True if file's info matches the requirements for current runtime or False if not.
Definition at line 285 of file runtime_freq_wrapper.py.
Referenced by metplus.wrappers.grid_diag_wrapper.GridDiagWrapper.subset_input_files(), and metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.subset_input_files().
get_all_files()
def metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.get_all_files (self, custom = None)
Get all files that can be processed with the app.
Some wrappers like UserScript do not need to obtain a list of possible files. In this case, the function returns an empty dictionary.
Returns
A dictionary where the key is the type of data that was found, i.e. fcst or obs, and the value is a list of files that fit in that category
Definition at line 223 of file runtime_freq_wrapper.py.
Referenced by metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.run_all_times_custom().
get_files_from_time()
def metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.get_files_from_time (self, time_info)
Create dictionary containing time information (key time_info) and any relevant files for that runtime.
Parameters
time_info dictionary containing time information
Returns
dictionary containing time_info dict and any relevant files with a key representing a description of that file
Definition at line 274 of file runtime_freq_wrapper.py.
Referenced by metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.get_all_files().
run_all_times_custom()
def metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.run_all_times_custom (self, custom)
Run the wrapper based on the time frequency specified.
Returns
True on success, False on failure
Definition at line 100 of file runtime_freq_wrapper.py.
run_at_time()
def metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.run_at_time (self, input_dict)
Runs the command for a given run time.
This function loops over the list of forecast leads and list of custom loops and runs once for each combination Args:
Parameters
input_dict dictionary containing time information
Definition at line 196 of file runtime_freq_wrapper.py.
Referenced by metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), and metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times().
Member Data Documentation
FREQ_OPTIONS
list metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.FREQ_OPTIONS static
Initial value:
=  ['RUN_ONCE',
                    'RUN_ONCE_PER_INIT_OR_VALID',
                    'RUN_ONCE_PER_LEAD',
                    'RUN_ONCE_FOR_EACH'
                    ]
Definition at line 30 of file runtime_freq_wrapper.py.
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/release-4.0.0-beta3/METplus/metplus/wrappers/runtime_freq_wrapper.py