METplus: metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper Class Reference
metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper Class Reference
Wraps the MET tool pcp_combine to combine or divide precipitation accumulations.
Detailed Description
Wraps the MET tool pcp_combine to combine or divide precipitation accumulations.
Definition at line 30 of file pcp_combine_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def create_c_dict (self)
def set_fcst_or_obs_dict_items (self, d_type, c_dict)
def clear (self)
def add_input_file (self, filename, addon)
def get_dir_and_template (self, data_type, in_or_out)
def getLowestForecastFile (self, valid_time, dtype, template)
Find the lowest forecast hour that corresponds to the valid time Args:
def get_daily_file (self, time_info, accum, data_src, file_template)
Pull accumulation out of file that contains a full day of data Args:
def get_addon (self, accum_dict, search_accum, search_time)
def find_input_file (self, in_template, init_time, valid_time, search_accum, data_src)
def get_template_accum (self, accum_dict, search_time, lead, data_src)
def get_accumulation (self, time_info, accum, data_src)
Find files to combine to build the desired accumulation Args:
def get_command (self)
def run_at_time_once (self, time_info, var_list, data_src)
def run_at_time_one_field (self, time_info, var_info, data_src)
def setup_subtract_method (self, time_info, var_info, data_src)
Setup pcp_combine to subtract two files to build desired accumulation Args:
def setup_sum_method (self, time_info, var_info, data_src)
Setup pcp_combine to build desired accumulation based on init/valid times and accumulations Args:
def setup_add_method (self, time_info, var_info, data_src)
Setup pcp_combine to add files to build desired accumulation Args:
def setup_derive_method (self, time_info, var_info, data_src)
Setup pcp_combine to derive stats Args:
def setup_user_method (self, time_info, data_src)
Setup pcp_combine to call user defined command Args:
def build_input_accum_list (self, data_src, time_info)
Public Attributes
app_name
app_path
inaddons
method
pcp_dir
pcp_regex
init_time
valid_time
in_accum
out_accum
field_name
field_level
output_name
name
compress
user_command
isOK
field_extra
outfile
outdir
input_dir
Static Public Attributes
list valid_run_methods = ['ADD', 'SUM', 'SUBTRACT', 'DERIVE', 'USER_DEFINED']
Member Function Documentation
get_accumulation()
def metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation (self, time_info, accum, data_src)
Find files to combine to build the desired accumulation Args:
Parameters
time_info dictionary containing time information
accum desired accumulation to build
data_src type of data (FCST or OBS) bool
Returns
True if full set of files to build accumulation is found
Definition at line 401 of file pcp_combine_wrapper.py.
Referenced by metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_add_method(), and metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_derive_method().
get_daily_file()
def metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_daily_file (self, time_info, accum, data_src, file_template)
Pull accumulation out of file that contains a full day of data Args:
Parameters
time_info dictionary containing timing information
accum accumulation to extract from file
data_src type of data (FCST or OBS)
file_template filename template to search bool
Returns
True if file was added to output list, False if not
Definition at line 252 of file pcp_combine_wrapper.py.
Referenced by metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
getLowestForecastFile()
def metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.getLowestForecastFile (self, valid_time, dtype, template)
Find the lowest forecast hour that corresponds to the valid time Args:
Parameters
valid_time valid time to search
dtype data type (FCST or OBS) to get filename template string
Returns
Path to file with the lowest forecast hour
Definition at line 202 of file pcp_combine_wrapper.py.
Referenced by metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_daily_file().
setup_add_method()
def metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_add_method (self, time_info, var_info, data_src)
Setup pcp_combine to add files to build desired accumulation Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information data_src data type (FCST or OBS) string
Returns
path to output file
Definition at line 838 of file pcp_combine_wrapper.py.
Referenced by metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
setup_derive_method()
def metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_derive_method (self, time_info, var_info, data_src)
Setup pcp_combine to derive stats Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information data_src data type (FCST or OBS) string
Returns
path to output file
Definition at line 897 of file pcp_combine_wrapper.py.
Referenced by metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
setup_subtract_method()
def metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_subtract_method (self, time_info, var_info, data_src)
Setup pcp_combine to subtract two files to build desired accumulation Args:
Parameters
time_info object containing timing information
var_info object containing variable information data_src data type (FCST or OBS) string
Returns
path to output file
Definition at line 642 of file pcp_combine_wrapper.py.
Referenced by metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
setup_sum_method()
def metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_sum_method (self, time_info, var_info, data_src)
Setup pcp_combine to build desired accumulation based on init/valid times and accumulations Args:
Parameters
time_info object containing timing information
var_info object containing variable information data_src data type (FCST or OBS) string
Returns
path to output file
Definition at line 756 of file pcp_combine_wrapper.py.
Referenced by metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
setup_user_method()
def metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_user_method (self, time_info, data_src)
Setup pcp_combine to call user defined command Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information data_src data type (FCST or OBS) string
Returns
path to output file
Definition at line 956 of file pcp_combine_wrapper.py.
Referenced by metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/release-4.0.0-beta3/METplus/metplus/wrappers/pcp_combine_wrapper.py