METplus: wrappers.tc_pairs_wrapper.TCPairsWrapper Class Reference
wrappers.tc_pairs_wrapper.TCPairsWrapper Class Reference
Wraps the MET tool, tc_pairs to parse and match ATCF_by_pairs adeck and bdeck files.
Detailed Description
Wraps the MET tool, tc_pairs to parse and match ATCF_by_pairs adeck and bdeck files.
Pre-processes extra tropical cyclone data.
Definition at line 38 of file tc_pairs_wrapper.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
Create a dictionary containing all the values set in the config file.
def run_all_times (self)
Build up the command to invoke the MET tool tc_pairs.
def run_at_time (self, input_dict)
Create the arguments to run MET tc_pairs Args: input_dict dictionary containing init or valid time Returns:
def run_at_time_loop_string (self, input_dict)
Create the arguments to run MET tc_pairs Args: input_dict dictionary containing init or valid time Returns:
def set_environment_variables (self, time_info)
Set up all the environment variables that are assigned in the METplus config file which are to be used by the MET TC-pairs config file.
def process_data (self, basin, cyclone, model_list, time_info)
Find requested files and run tc_pairs Args:
def find_deck_files (self, deck, basin, cyclone, model_list, time_info)
Find ADECK or EDECK files that correspond to the BDECk file found Args:
def reformat_files (self, file_list, deck_type, time_info)
Reformat track data to match expected ATCF format Args:
def get_command (self)
Over-ride CommandBuilder's get_command because unlike other MET tools, tc_pairs handles input files differently- namely, through flags -adeck and -bdeck and doesn't require an output file, as there is a default.
def read_modify_write_file (self, in_csvfile, storm_month, missing_values, out_csvfile)
Reads, modifies and writes file Args:
Public Attributes
app_name
app_path
adeck
bdeck
edeck
isOK
outdir
outfile
Member Function Documentation
create_c_dict()
def wrappers.tc_pairs_wrapper.TCPairsWrapper.create_c_dict (self)
Create a dictionary containing all the values set in the config file.
This will make it easier for unit testing.
Args:
Returns: c_dict - A dictionary of the values from the config file
Definition at line 52 of file tc_pairs_wrapper.py.
find_deck_files()
def wrappers.tc_pairs_wrapper.TCPairsWrapper.find_deck_files (self, deck, basin, cyclone, model_list, time_info)
Find ADECK or EDECK files that correspond to the BDECk file found Args:
Parameters
deck type of deck (A or E)
basin region of storm from config
cyclone ID number of cyclone from config
model_list list of models that be available
time_info object containing timing information to process
Definition at line 594 of file tc_pairs_wrapper.py.
Referenced by wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data().
get_command()
def wrappers.tc_pairs_wrapper.TCPairsWrapper.get_command (self)
Over-ride CommandBuilder's get_command because unlike other MET tools, tc_pairs handles input files differently- namely, through flags -adeck and -bdeck and doesn't require an output file, as there is a default.
Build command to run from arguments
Definition at line 665 of file tc_pairs_wrapper.py.
Referenced by wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.build(), wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data(), wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), and wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once().
process_data()
def wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data (self, basin, cyclone, model_list, time_info)
Find requested files and run tc_pairs Args:
Parameters
basin region of storm from config
cyclone ID number of cyclone from config
model_list list of models that be available
time_info object containing timing information to process
Definition at line 451 of file tc_pairs_wrapper.py.
Referenced by wrappers.tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string().
read_modify_write_file()
def wrappers.tc_pairs_wrapper.TCPairsWrapper.read_modify_write_file (self, in_csvfile, storm_month, missing_values, out_csvfile)
Reads, modifies and writes file Args:
Parameters
in_csvfile input csv file that is being parsed
storm_month The storm month
missing_values a tuple where (MISSING_VAL_TO_REPLACE, MISSING_VAL)
out_csvfile the output csv file
logger the log where logging is directed
Definition at line 712 of file tc_pairs_wrapper.py.
Referenced by wrappers.tc_pairs_wrapper.TCPairsWrapper.get_command(), and wrappers.tc_pairs_wrapper.TCPairsWrapper.reformat_files().
reformat_files()
def wrappers.tc_pairs_wrapper.TCPairsWrapper.reformat_files (self, file_list, deck_type, time_info)
Reformat track data to match expected ATCF format Args:
Parameters
file_list list of files to reformat
deck_type type of deck (A or E)
time_info object with timing information to get storm month Returns: list of output files that are in ATCF format
Definition at line 632 of file tc_pairs_wrapper.py.
Referenced by wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data().
set_environment_variables()
def wrappers.tc_pairs_wrapper.TCPairsWrapper.set_environment_variables (self, time_info)
Set up all the environment variables that are assigned in the METplus config file which are to be used by the MET TC-pairs config file.
Args: nothing - retrieves necessary MET+ config values via class attributes
Returns: nothing - sets the environment variables
Definition at line 298 of file tc_pairs_wrapper.py.
Referenced by wrappers.make_plots_wrapper.MakePlotsWrapper.create_c_dict(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper.run_at_time(), wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string(), wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once(), and wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/tc_pairs_wrapper.py