METplus: metplus.wrappers.cyclone_plotter_wrapper.CyclonePlotterWrapper Class Reference
metplus.wrappers.cyclone_plotter_wrapper.CyclonePlotterWrapper Class Reference
Generate plots of extra tropical storm forecast tracks.
Detailed Description
Generate plots of extra tropical storm forecast tracks.
Reads input from ATCF files generated from MET TC-Pairs
Definition at line 32 of file cyclone_plotter_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def run_all_times (self)
Calls the defs needed to create the cyclone plots run_all_times() is required by CommandBuilder.
def retrieve_data (self)
Retrieve data from track files and return the min and max lon.
def get_columns_and_indices (self, header)
def create_plot (self)
Create the plot, using Cartopy.
Static Public Member Functions
def extract_date_and_time_from_init (init_time_str)
def extract_lead_hr (lead_str)
def set_lead_group (track_dict, init_hh)
Sets the position indicator key to 0 if init hour is 0 or 12, and 6 if init hour is 6 or 18.
def rescale_lon (lon)
Rescales longitude, using the same logic employed by MET.
Public Attributes
app_name
input_data
output_dir
init_date
init_hr
model
title
gen_ascii
unique_storm_id
storm_id_dict
columns_of_interest
circle_marker
cross_marker
Member Function Documentation
extract_date_and_time_from_init()
def metplus.wrappers.cyclone_plotter_wrapper.CyclonePlotterWrapper.extract_date_and_time_from_init (init_time_str) static
Extract and return the YYYYMMDD portion and the
    hh portion from the init time taken from the .tcst file.
Definition at line 292 of file cyclone_plotter_wrapper.py.
Referenced by metplus.wrappers.cyclone_plotter_wrapper.CyclonePlotterWrapper.retrieve_data().
extract_lead_hr()
def metplus.wrappers.cyclone_plotter_wrapper.CyclonePlotterWrapper.extract_lead_hr (lead_str) static
Extract and return the lead hours from the hhmmss lead string.
Definition at line 306 of file cyclone_plotter_wrapper.py.
Referenced by metplus.wrappers.cyclone_plotter_wrapper.CyclonePlotterWrapper.retrieve_data().
get_columns_and_indices()
def metplus.wrappers.cyclone_plotter_wrapper.CyclonePlotterWrapper.get_columns_and_indices (self, header)
Parse the header for the columns of interest and store the
    information in a dictionary where the key is the column name
    and value is the index/column number.
    Returns:
column_dict:  A dictionary containing the column name
              and its index
Definition at line 273 of file cyclone_plotter_wrapper.py.
Referenced by metplus.wrappers.cyclone_plotter_wrapper.CyclonePlotterWrapper.retrieve_data().
rescale_lon()
def metplus.wrappers.cyclone_plotter_wrapper.CyclonePlotterWrapper.rescale_lon (lon) static
Rescales longitude, using the same logic employed by MET.
Definition at line 548 of file cyclone_plotter_wrapper.py.
retrieve_data()
def metplus.wrappers.cyclone_plotter_wrapper.CyclonePlotterWrapper.retrieve_data (self)
Retrieve data from track files and return the min and max lon.
Returns: None
Definition at line 86 of file cyclone_plotter_wrapper.py.
Referenced by metplus.wrappers.cyclone_plotter_wrapper.CyclonePlotterWrapper.run_all_times().
set_lead_group()
def metplus.wrappers.cyclone_plotter_wrapper.CyclonePlotterWrapper.set_lead_group (track_dict, init_hh) static
Sets the position indicator key to 0 if init hour is 0 or 12, and 6 if init hour is 6 or 18.
This is used to determine which symbol to use, a '+' or 'o' when plotting track points.
Definition at line 538 of file cyclone_plotter_wrapper.py.
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/METplus/metplus/wrappers/cyclone_plotter_wrapper.py