METplus: wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper Class Reference
wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper Class Reference
Wrapper to utilize Python Embedding in the MET tools to read in data using a python script.
Detailed Description
Wrapper to utilize Python Embedding in the MET tools to read in data using a python script.
Definition at line 24 of file py_embed_ingest_wrapper.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
def get_ingest_items (self, item_type, index, ingest_script_addons)
def run_at_time (self, input_dict)
Do some processing for the current run time (init or valid) Args:
def run_at_time_lead (self, time_info)
Public Attributes
app_name
isOK
Member Function Documentation
run_at_time()
def wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper.run_at_time (self, input_dict)
Do some processing for the current run time (init or valid) Args:
Parameters
input_dict dictionary containing time information of current run generally contains 'now' (current) time and 'init' or 'valid' time
Definition at line 120 of file py_embed_ingest_wrapper.py.
Referenced by wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_all_times(), and wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/py_embed_ingest_wrapper.py