METplus: metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper Class Reference
metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper Class Reference
Wrapper to the MET tool stat_analysis which is used to filter and summarize data from MET's point_stat, grid_stat, ensemble_stat, and wavelet_stat.
Detailed Description
Wrapper to the MET tool stat_analysis which is used to filter and summarize data from MET's point_stat, grid_stat, ensemble_stat, and wavelet_stat.
Definition at line 25 of file stat_analysis_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def get_command (self)
def create_c_dict (self)
Create a data structure (dictionary) that contains all the values set in the configuration files that are common for stat_analysis_wrapper.py.
def c_dict_error_check (self, c_dict)
def read_field_lists_from_config (self, field_dict)
Get field list configuration variables and add to dictionary.
def check_MakePlots_config (self, c_dict)
def list_to_str (self, list_of_values, add_quotes=True)
Turn a list of values into a single string so it can be set to an environment variable and read by the MET stat_analysis config file.
def set_lists_loop_or_group (self, c_dict)
Determine whether the lists from the METplus config file should treat the items in that list as a group or items to be looped over based on user settings, the values in the list, and process being run.
def format_thresh (self, thresh)
Format thresholds for file naming.
def build_stringsub_dict (self, lists_to_loop, lists_to_group, config_dict)
Build a dictionary with list names, dates, and commonly used identifiers to pass to string_template_substitution.
def get_output_filename (self, output_type, filename_template, filename_type, lists_to_loop, lists_to_group, config_dict)
Create a file name for stat_analysis output.
def get_lookin_dir (self, dir_path, lists_to_loop, lists_to_group, config_dict)
Fill in necessary information to get the path to the lookin directory to pass to stat_analysis.
def format_valid_init (self, config_dict)
Format the valid and initialization dates and hours for the MET stat_analysis config file.
def parse_model_info (self)
Parse for model information.
def get_level_list (self, data_type)
Read forecast or observation level list from config.
def process_job_args (self, job_type, job, model_info, lists_to_loop_items, lists_to_group_items, runtime_settings_dict)
def get_runtime_settings_dict_list (self)
def get_runtime_settings (self, c_dict)
def get_field_units (self, index)
Get units of fcst and obs fields if set based on VAR<n> index index VAR<n> index corresponding to other [FCST/OBS] info.
def get_c_dict_list (self)
def add_other_lists_to_c_dict (self, c_dict)
Using GROUP_LIST_ITEMS and LOOP_LIST_ITEMS, add lists from self.c_dict that are not already in c_dict.
def get_model_obtype_and_lookindir (self, runtime_settings_dict, loop_lists, group_lists)
Reads through model info dictionaries for given run.
def get_job_info (self, model_info, runtime_settings_dict, loop_lists, group_lists)
Get job information and concatenate values into a string model_info model information to use to determine output file paths runtime_settings_dict dictionary containing all settings used in next run.
def run_stat_analysis (self)
This runs stat_analysis over a period of valid or initialization dates for a job defined by the user.
def run_stat_analysis_job (self, runtime_settings_dict_list)
Sets environment variables need to run StatAnalysis jobs and calls the tool for each job.
def create_output_directories (self, runtime_settings_dict)
Check if output filename is set for dump_row or out_stat.
def run_all_times (self)
def run_at_time (self, input_dict)
Public Attributes
app_path
app_name
runMakePlots
MakePlotsWrapper
forMakePlots
job_args
lookindir
Static Public Attributes
list field_lists
list format_lists
list expected_config_lists
list force_group_for_make_plots_lists
list list_categories = ['GROUP_LIST_ITEMS', 'LOOP_LIST_ITEMS']
list list_categories_make_plots = ['GROUP_LIST_ITEMS_MAKE_PLOTS', 'LOOP_LIST_ITEMS_MAKE_PLOTS']
list format_later_list
Member Function Documentation
add_other_lists_to_c_dict()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.add_other_lists_to_c_dict (self, c_dict)
Using GROUP_LIST_ITEMS and LOOP_LIST_ITEMS, add lists from self.c_dict that are not already in c_dict.
Parameters
c_dict dictionary to add values to
Definition at line 1552 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_field_units().
build_stringsub_dict()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.build_stringsub_dict (self, lists_to_loop, lists_to_group, config_dict)
Build a dictionary with list names, dates, and commonly used identifiers to pass to string_template_substitution.
Args: lists_to_loop - list of all the list names whose items are being grouped together lists_to group - list of all the list names whose items are being looped over config_dict - dictionary containing the configuration information
Returns: stringsub_dict - dictionary containing the formatted information to pass to the string_template_substitution
Definition at line 451 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_lookin_dir(), and metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_output_filename().
create_c_dict()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.create_c_dict (self)
Create a data structure (dictionary) that contains all the values set in the configuration files that are common for stat_analysis_wrapper.py.
Args:
Returns: c_dict - a dictionary containing the settings in the configuration files unique to the wrapper
Definition at line 105 of file stat_analysis_wrapper.py.
create_output_directories()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.create_output_directories (self, runtime_settings_dict)
Check if output filename is set for dump_row or out_stat.
If set, Check if the file already exists and if it should be skipped.
Parameters
runtime_settings_dict dictionary containing filename info
Returns
True if job should be run, False if it should be skipped
Definition at line 1708 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
format_thresh()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.format_thresh (self, thresh)
Format thresholds for file naming.
Args:
Parameters
thresh string of the thresholds. Can be a comma-separated list, i.e. gt3,<=5.5, ==7
 @returns string of comma-separated list of the threshold(s) with letter format, i.e. gt3, le5.5, eq7
Definition at line 430 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.build_stringsub_dict(), and metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_field_units().
format_valid_init()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.format_valid_init (self, config_dict)
Format the valid and initialization dates and hours for the MET stat_analysis config file.
Args: config_dict - dictionary containing the configuration information
Returns: config_dict - dictionary containing the edited configuration information for valid and initialization dates and hours
Definition at line 1032 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_level_list().
get_field_units()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_field_units (self, index)
Get units of fcst and obs fields if set based on VAR<n> index index VAR<n> index corresponding to other [FCST/OBS] info.
Returns
tuple containing forecast and observation units respectively
Definition at line 1420 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_field_units().
get_job_info()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_job_info (self, model_info, runtime_settings_dict, loop_lists, group_lists)
Get job information and concatenate values into a string model_info model information to use to determine output file paths runtime_settings_dict dictionary containing all settings used in next run.
Returns
string containing job information to pass to StatAnalysis config file
Definition at line 1625 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_level_list().
get_level_list()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_level_list (self, data_type)
Read forecast or observation level list from config.
Format list items to match the format expected by StatAnalysis by removing parenthesis and any quotes, then adding back single quotes Args:
Parameters
data_type type of list to get, FCST or OBS
Returns
list containing the formatted level list
Definition at line 1269 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.read_field_lists_from_config().
get_lookin_dir()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_lookin_dir (self, dir_path, lists_to_loop, lists_to_group, config_dict)
Fill in necessary information to get the path to the lookin directory to pass to stat_analysis.
Args: dir_path - string of the user provided directory path lists_to_loop - list of all the list names whose items are being grouped together lists_to group - list of all the list names whose items are being looped over config_dict - dictionary containing the configuration information
Returns: lookin_dir - string of the filled directory from dir_path
Definition at line 997 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_model_obtype_and_lookindir().
get_model_obtype_and_lookindir()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_model_obtype_and_lookindir (self, runtime_settings_dict, loop_lists, group_lists)
Reads through model info dictionaries for given run.
Sets lookindir command line argument. Sets MODEL and OBTYPE values in runtime setting dictionary.
Parameters
runtime_settings_dict dictionary containing all settings used in next run
Returns
last model info dictionary is successful, None if not.
Definition at line 1571 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_level_list().
get_output_filename()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_output_filename (self, output_type, filename_template, filename_type, lists_to_loop, lists_to_group, config_dict)
Create a file name for stat_analysis output.
Args: output_type - string for the type of stat_analysis output, either dump_row or out_stat filename_template - string of the template to be used to create the file name filename_type - string of the source of the template being used, either default or user lists_to_loop - list of all the list names whose items are being grouped together lists_to group - list of all the list names whose items are being looped over config_dict - dictionary containing the configuration information
Returns: output_filename - string of the filled file name template
Definition at line 865 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.build_stringsub_dict(), and metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_level_list().
list_to_str()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.list_to_str (self, list_of_values, add_quotes = True)
Turn a list of values into a single string so it can be set to an environment variable and read by the MET stat_analysis config file.
Args:
Parameters
list_of_values - list of values, i.e. ['value1', 'value2']
add_quotes if True, add quotation marks around values default is True
Returns
string created from list_of_values with the values separated by commas, i.e. '"value1", "value2"' or 1, 3 if add_quotes is False
Definition at line 334 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_level_list(), and metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.get_model_obtype_and_lookindir().
parse_model_info()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.parse_model_info (self)
Parse for model information.
Args:
Returns: model_list - list of dictionaries containing model information
Definition at line 1180 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.create_c_dict().
read_field_lists_from_config()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.read_field_lists_from_config (self, field_dict)
Get field list configuration variables and add to dictionary.
Parameters
field_dict dictionary to hold output values
Returns
True if all lists are empty or False if any have a value
Definition at line 255 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.create_c_dict().
run_stat_analysis_job()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job (self, runtime_settings_dict_list)
Sets environment variables need to run StatAnalysis jobs and calls the tool for each job.
Args:
Parameters
runtime_settings_dict_list list of dictionaries containing information needed to run a StatAnalysis job
Definition at line 1674 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis().
set_lists_loop_or_group()
def metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.set_lists_loop_or_group (self, c_dict)
Determine whether the lists from the METplus config file should treat the items in that list as a group or items to be looped over based on user settings, the values in the list, and process being run.
Args:
Parameters
group_items list of the METplus config list names to group the list's items set by user
loop_items list of the METplus config list names to loop over the list's items set by user
config_dict dictionary containing the configuration information
Returns
tuple containing lists_to_group_items (list of all the list names whose items are being grouped together) and lists_to_loop_items (list of all the list names whose items are being looped over)
Definition at line 356 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.create_c_dict().
Member Data Documentation
expected_config_lists
list metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.expected_config_lists static
Initial value:
=  ['MODEL_LIST',
                             'DESC_LIST',
                             'VX_MASK_LIST',
                             'INTERP_MTHD_LIST',
                             'INTERP_PNTS_LIST',
                             'COV_THRESH_LIST',
                             'ALPHA_LIST',
                             'LINE_TYPE_LIST',
                             ] + format_lists + field_lists
Definition at line 49 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.create_c_dict(), and metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.set_lists_loop_or_group().
field_lists
list metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.field_lists static
Initial value:
=  ['FCST_VAR_LIST',
                   'OBS_VAR_LIST',
                   'FCST_UNITS_LIST',
                   'OBS_UNITS_LIST',
                   'FCST_THRESH_LIST',
                   'OBS_THRESH_LIST',
                   'FCST_LEVEL_LIST',
                   'OBS_LEVEL_LIST',
                   ]
Definition at line 31 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.create_c_dict(), and metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.read_field_lists_from_config().
force_group_for_make_plots_lists
list metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.force_group_for_make_plots_lists static
Initial value:
=  ['MODEL_LIST',
                                        'FCST_LEAD_LIST',
                                        'OBS_LEAD_LIST',
                                        'FCST_LEVEL_LIST',
                                        'OBS_LEVEL_LIST',
                                        'FCST_THRESH_LIST',
                                        'OBS_THRESH_LIST',
                                        'FCST_UNITS_LIST',
                                        'OBS_UNITS_LIST',
                                       ]
Definition at line 59 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.build_stringsub_dict(), and metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.set_lists_loop_or_group().
format_later_list
list metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.format_later_list static
Initial value:
=  [
        'MODEL_LIST', 'FCST_VALID_HOUR_LIST', 'OBS_VALID_HOUR_LIST',
        'FCST_INIT_HOUR_LIST', 'OBS_INIT_HOUR_LIST'
    ]
Definition at line 73 of file stat_analysis_wrapper.py.
format_lists
list metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.format_lists static
Initial value:
=  ['FCST_VALID_HOUR_LIST',
                    'FCST_INIT_HOUR_LIST',
                    'OBS_VALID_HOUR_LIST',
                    'OBS_INIT_HOUR_LIST',
                    'FCST_LEAD_LIST',
                    'OBS_LEAD_LIST',
                    ]
Definition at line 41 of file stat_analysis_wrapper.py.
Referenced by metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.create_c_dict().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/metplus/wrappers/stat_analysis_wrapper.py