METplus: wrappers.point_stat_wrapper.PointStatWrapper Class Reference
wrappers.point_stat_wrapper.PointStatWrapper Class Reference
Wrapper to the MET tool, Point-Stat.
Detailed Description
Wrapper to the MET tool, Point-Stat.
Definition at line 20 of file point_stat_wrapper.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
Create a dictionary that holds all the values set in the METplus config file for the point-stat wrapper.
def add_obs_valid_args (self, time_info)
def set_environment_variables (self, fcst_field=None, obs_field=None, time_info=None)
Set all the environment variables in the MET config file to the corresponding values in the METplus config file.
Public Attributes
app_name
app_path
isOK
Member Function Documentation
create_c_dict()
def wrappers.point_stat_wrapper.PointStatWrapper.create_c_dict (self)
Create a dictionary that holds all the values set in the METplus config file for the point-stat wrapper.
Returns: c_dict - A dictionary containing the key-value pairs set in the METplus configuration file.
Definition at line 29 of file point_stat_wrapper.py.
set_environment_variables()
def wrappers.point_stat_wrapper.PointStatWrapper.set_environment_variables (self, fcst_field = None, obs_field = None, time_info = None)
Set all the environment variables in the MET config file to the corresponding values in the METplus config file.
Args:
Returns: None - invokes parent class, CommandBuilder add_env_var to add each environment variable to run the
Definition at line 131 of file point_stat_wrapper.py.
Referenced by wrappers.make_plots_wrapper.MakePlotsWrapper.create_c_dict(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper.run_at_time(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string(), wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once(), and wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/point_stat_wrapper.py