METplus: wrappers.tcrmw_wrapper.TCRMWWrapper Class Reference
wrappers.tcrmw_wrapper.TCRMWWrapper Class Reference
Detailed Description
Definition at line 26 of file tcrmw_wrapper.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
def set_environment_variables (self, time_info)
Set environment variables that will be read by the MET config file.
def get_command (self)
def run_at_time (self, input_dict)
Runs the MET application for a given run time.
def run_at_time_once (self, time_info)
Process runtime and try to build command to run ascii2nc Args:
def set_data_field (self, time_info)
Get list of fields from config to process.
def find_input_files (self, time_info)
Get DECK file and list of input data files and set c_dict items.
def set_command_line_arguments (self, time_info)
Public Attributes
app_name
app_path
isOK
Member Function Documentation
find_input_files()
def wrappers.tcrmw_wrapper.TCRMWWrapper.find_input_files (self, time_info)
Get DECK file and list of input data files and set c_dict items.
Args:
Parameters
time_info time dictionary to use for string substitution
Returns
Input file list if all files were found, None if not.
Definition at line 369 of file tcrmw_wrapper.py.
Referenced by wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once().
run_at_time()
def wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time (self, input_dict)
Runs the MET application for a given run time.
This function loops over the list of forecast leads and runs the application for each. Args:
Parameters
input_dict dictionary containing timing information
Definition at line 285 of file tcrmw_wrapper.py.
run_at_time_once()
def wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once (self, time_info)
Process runtime and try to build command to run ascii2nc Args:
Parameters
time_info dictionary containing timing information
Definition at line 306 of file tcrmw_wrapper.py.
Referenced by wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time().
set_data_field()
def wrappers.tcrmw_wrapper.TCRMWWrapper.set_data_field (self, time_info)
Get list of fields from config to process.
Build list of field info that are formatted to be read by the MET config file. Set DATA_FIELD item of c_dict with the formatted list of fields. Args:
Parameters
time_info time dictionary to use for string substitution
Returns
True if field list could be built, False if not.
Definition at line 337 of file tcrmw_wrapper.py.
Referenced by wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once().
set_environment_variables()
def wrappers.tcrmw_wrapper.TCRMWWrapper.set_environment_variables (self, time_info)
Set environment variables that will be read by the MET config file.
Reformat as needed. Print list of variables that were set and their values. Args:
Parameters
time_info dictionary containing timing info from current run
Definition at line 169 of file tcrmw_wrapper.py.
Referenced by wrappers.make_plots_wrapper.MakePlotsWrapper.create_c_dict(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation(), wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper.run_at_time(), wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once(), and wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/tcrmw_wrapper.py