METplus: metplus.wrappers.gempak_to_cf_wrapper.GempakToCFWrapper Class Reference
metplus.wrappers.gempak_to_cf_wrapper.GempakToCFWrapper Class Reference
Detailed Description
Definition at line 26 of file gempak_to_cf_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def create_c_dict (self)
Create dictionary from config items to be used in the wrapper Allows developer to reference config items without having to know the type and consolidates config get calls so it is easier to see which config variables are used in the wrapper.
def get_command (self)
def run_at_time (self, input_dict)
Runs the MET application for a given run time.
def run_at_time_once (self, time_info)
Runs the MET application for a given time and forecast lead combination Args:
Public Attributes
app_name
app_path
outfile
Member Function Documentation
run_at_time()
def metplus.wrappers.gempak_to_cf_wrapper.GempakToCFWrapper.run_at_time (self, input_dict)
Runs the MET application for a given run time.
Processing forecast or observation data is determined by conf variables. This function loops over the list of forecast leads and runs the application for each. Args:
Parameters
input_dict dictionary containing timing information
Definition at line 72 of file gempak_to_cf_wrapper.py.
Referenced by metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), and metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times().
run_at_time_once()
def metplus.wrappers.gempak_to_cf_wrapper.GempakToCFWrapper.run_at_time_once (self, time_info)
Runs the MET application for a given time and forecast lead combination Args:
Parameters
time_info dictionary containing timing information
Definition at line 98 of file gempak_to_cf_wrapper.py.
Referenced by metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.run_all_times_custom(), metplus.wrappers.reformat_gridded_wrapper.ReformatGriddedWrapper.run_at_time(), metplus.wrappers.gempak_to_cf_wrapper.GempakToCFWrapper.run_at_time(), metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time(), metplus.wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time(), metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.run_at_time(), metplus.wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time(), metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time(), and metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_once_per_lead().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus/metplus/wrappers/gempak_to_cf_wrapper.py