METplus: wrappers.command_builder.CommandBuilder Class Reference
wrappers.command_builder.CommandBuilder Class Reference
Common functionality to wrap all MET applications.
Detailed Description
Common functionality to wrap all MET applications.
Definition at line 33 of file command_builder.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def set_environment_variables (self, time_info=None)
Set environment variables that will be read set when running this tool.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def format_regrid_to_grid (self, to_grid)
def add_common_envs (self, time_info=None)
def print_all_envs (self)
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def print_env (self)
Print all environment variables set for this application.
def print_env_copy (self, var_list=None)
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def print_user_env_items (self)
Prints user environment variables in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info=None, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info=None, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_obs_offset (self, time_info, var_info=None, mandatory=True, return_list=False)
Finds the observation file to compare, looping through offset list until a file is found Args:
def find_data (self, time_info, var_info=None, data_type='', mandatory=True, return_list=False, allow_dir=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False, allow_dir=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info)
Build full path for expected output file and check if it exists.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def get_output_prefix (self, time_info)
def add_field_info_to_time_info (self, time_info, field_info)
Add name and level values from field info to time info dict to be used in string substitution Args:
def set_current_field_config (self, field_info=None)
Sets config variables for current fcst/obs name/level that can be referenced by other config variables such as OUTPUT_PREFIX.
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_field_info (self, d_type, v_name, v_level='', v_thresh=[], v_extra='')
Format field information into format expected by MET config file Args:
def get_verification_mask (self, time_info)
If verification mask template is set in the config file, use it to find the verification mask filename.
def get_command (self)
Builds the command to run the MET application string.
def build_and_run_command (self)
def build (self)
Build and run command.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
def set_time_dict_for_single_runtime (self, c_dict)
def create_met_config_dictionary_string (self, dict_name, item_list)
Build string containing dictionary from a MET configuration file with any items that were set in the user's METplus configuration.
def set_c_dict_list (self, c_dict, mp_config_name, met_config_name, c_dict_key=None, remove_quotes=False)
Get list from METplus configuration file and format it to be passed into a MET configuration file.
def set_c_dict_string (self, c_dict, mp_config_name, met_config_name, c_dict_key=None)
Get string from METplus configuration file and format it to be passed into a MET configuration file.
def set_c_dict_number (self, c_dict, num_type, mp_config_name, met_config_name, c_dict_key=None)
Get integer from METplus configuration file and format it to be passed into a MET configuration file.
def set_c_dict_int (self, c_dict, mp_config_name, met_config_name, c_dict_key=None)
def set_c_dict_float (self, c_dict, mp_config_name, met_config_name, c_dict_key=None)
def set_c_dict_thresh (self, c_dict, mp_config_name, met_config_name, c_dict_key=None)
Public Attributes
isOK
errors
config
logger
env_list
debug
args
input_dir
infiles
outdir
outfile
param
all_commands
env
c_dict
cmdrunner
Member Function Documentation
add_field_info_to_time_info()
def wrappers.command_builder.CommandBuilder.add_field_info_to_time_info (self, time_info, field_info)
Add name and level values from field info to time info dict to be used in string substitution Args:
Parameters
time_info time dictionary to add items to
field_info field dictionary to get values from
Definition at line 772 of file command_builder.py.
Referenced by wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_for_all_fields(), and wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_per_field().
check_for_python_embedding()
def wrappers.command_builder.CommandBuilder.check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
If it is not, return the field name. If it is, check if the input datatype is a valid Python Embedding string, set the c_dict item that sets the file_type in the MET config file accordingly, and set the output string to 'python_embedding. Used to set up Python Embedding input for MET tools that support multiple input files, such as MTD, EnsembleStat, and SeriesAnalysis. Args:
Parameters
input_type type of field input, i.e. FCST, OBS, ENS, POINT_OBS, GRID_OBS, or BOTH
var_info dictionary item containing field information for the current *_VAR<n>_* configs being handled
Returns
field name if not a python script, 'python_embedding' if it is, and None if configuration is invalid
Definition at line 804 of file command_builder.py.
Referenced by wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.get_all_field_info(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), and wrappers.mtd_wrapper.MTDWrapper.run_at_time_loop_string().
create_met_config_dictionary_string()
def wrappers.command_builder.CommandBuilder.create_met_config_dictionary_string (self, dict_name, item_list)
Build string containing dictionary from a MET configuration file with any items that were set in the user's METplus configuration.
Any variables that were not set will not be included in the dictionary string. Args:
Parameters
dict_name name of dictionary to create in all caps. This corresponds to the name of the METplus configuration variable and c_dict value. The lower-case name also matches the name of the MET dictionary item, i.e. FCST_GENESIS corresponds to METpluc configuration variables TC_GEN_FCST_GENESIS_VMAX_THRESH and TC_GEN_FCST_GENESIS_MSLP_THRESH and c_dict keys FCST_GENESIS_VMAX_THRESH and FCST_GENESIS_MSLP_THRESH and MET configuration dictionary fcst_genesis = {}.
item_list list of MET dictionary items that can be set, i.e. [VMAX_THRESH, MSLP_THRESH], which corresponds to vmax_thresh and mslp_thresh in the MET configuration dictionary specified with dict_name.
Returns
string of formatted MET dictionary or empty string if no relevant variables were set
Definition at line 1074 of file command_builder.py.
Referenced by wrappers.tc_gen_wrapper.TCGenWrapper.set_environment_variables().
find_and_check_output_file()
def wrappers.command_builder.CommandBuilder.find_and_check_output_file (self, time_info)
Build full path for expected output file and check if it exists.
If output file doesn't exist or it does exists and we are not skipping it then return True to run the tool. Otherwise return False to not run the tool Args:
Parameters
time_info time dictionary to use to fill out output file template
Returns
True if the app should be run or False if it should not
Definition at line 675 of file command_builder.py.
Referenced by wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.handle_output_file(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), wrappers.grid_diag_wrapper.GridDiagWrapper.run_at_time_once(), wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), wrappers.ascii2nc_wrapper.ASCII2NCWrapper.run_at_time_once(), wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), and wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once().
find_data()
def wrappers.command_builder.CommandBuilder.find_data (self, time_info, var_info = None, data_type = '', mandatory = True, return_list = False, allow_dir = False)
Finds the data file to compare Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
data_type type of data to find (i.e. FCST_ or OBS_)
mandatory if True, report error if not found, warning if not default is True string
Returns
Returns the path to an observation file
Definition at line 418 of file command_builder.py.
Referenced by wrappers.grid_diag_wrapper.GridDiagWrapper.find_input_file_list(), wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.find_input_files(), wrappers.tc_gen_wrapper.TCGenWrapper.find_input_files(), wrappers.tcrmw_wrapper.TCRMWWrapper.find_input_files(), wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.find_input_files(), wrappers.command_builder.CommandBuilder.find_model(), wrappers.command_builder.CommandBuilder.find_obs(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), and wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.run_at_time_all_fields().
find_model()
def wrappers.command_builder.CommandBuilder.find_model (self, time_info, var_info = None, mandatory = True, return_list = False)
Finds the model file to compare Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
mandatory if True, report error if not found, warning if not default is True string
Returns
Returns the path to an model file
Definition at line 343 of file command_builder.py.
Referenced by wrappers.compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_all_fields(), wrappers.mtd_wrapper.MTDWrapper.run_at_time_loop_string(), wrappers.mode_wrapper.MODEWrapper.run_at_time_one_field(), and wrappers.compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_one_field().
find_obs()
def wrappers.command_builder.CommandBuilder.find_obs (self, time_info, var_info = None, mandatory = True, return_list = False)
Finds the observation file to compare Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
mandatory if True, report error if not found, warning if not default is True string
Returns
Returns the path to an observation file
Definition at line 359 of file command_builder.py.
Referenced by wrappers.point2grid_wrapper.Point2GridWrapper.find_input_files(), wrappers.command_builder.CommandBuilder.find_obs_offset(), wrappers.mtd_wrapper.MTDWrapper.run_at_time_loop_string(), wrappers.ascii2nc_wrapper.ASCII2NCWrapper.run_at_time_once(), and wrappers.mode_wrapper.MODEWrapper.run_at_time_one_field().
find_obs_offset()
def wrappers.command_builder.CommandBuilder.find_obs_offset (self, time_info, var_info = None, mandatory = True, return_list = False)
Finds the observation file to compare, looping through offset list until a file is found Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
mandatory if True, report error if not found, warning if not default is True string
Returns
Returns tuple of the path to an observation file and the time_info object used to find the data so the value of offset can be preserved
Definition at line 375 of file command_builder.py.
Referenced by wrappers.pb2nc_wrapper.PB2NCWrapper.find_input_files(), wrappers.compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_all_fields(), and wrappers.compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_one_field().
get_command()
def wrappers.command_builder.CommandBuilder.get_command (self)
Builds the command to run the MET application string.
Returns
Returns a MET command with arguments that you can run
Definition at line 965 of file command_builder.py.
Referenced by wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.build(), wrappers.command_builder.CommandBuilder.build(), wrappers.command_builder.CommandBuilder.get_command(), wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data(), wrappers.compare_gridded_wrapper.CompareGriddedWrapper.process_fields(), wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.process_fields(), wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh(), wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), wrappers.gempak_to_cf_wrapper.GempakToCFWrapper.run_at_time_once(), wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_add_method(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_derive_method(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_subtract_method(), and wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_sum_method().
get_field_info()
def wrappers.command_builder.CommandBuilder.get_field_info (self, d_type, v_name, v_level = '', v_thresh = [], v_extra = '')
Format field information into format expected by MET config file Args:
Parameters
v_level level of data to extract
v_thresh threshold value to use in comparison
v_name name of field to process
v_extra additional field information to add if available
d_type type of data to find i.e. FCST or OBS string
Returns
Returns formatted field information
Definition at line 835 of file command_builder.py.
Referenced by wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.get_all_field_info(), wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh(), wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), wrappers.compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_all_fields(), wrappers.compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_one_field(), wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_for_all_fields(), wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_per_field(), wrappers.grid_diag_wrapper.GridDiagWrapper.set_data_field(), and wrappers.tcrmw_wrapper.TCRMWWrapper.set_data_field().
handle_fcst_and_obs_field()
def wrappers.command_builder.CommandBuilder.handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default = None, sec = 'config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
FCST_NAME, OBS_NAME, and NAME. If FCST_NAME and OBS_NAME both exist, they are used. If both are don't exist, NAME is used.
Definition at line 298 of file command_builder.py.
Referenced by wrappers.mode_wrapper.MODEWrapper.add_merge_config_file().
handle_window_once()
def wrappers.command_builder.CommandBuilder.handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
Parameters
c_dict dictionary to set items in
dtype type of data 'FCST' or 'OBS'
edge either 'BEGIN' or 'END'
Definition at line 171 of file command_builder.py.
Referenced by wrappers.command_builder.CommandBuilder.handle_window_variables().
handle_window_variables()
def wrappers.command_builder.CommandBuilder.handle_window_variables (self, c_dict, app_name, dtypes = ['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
Parameters
c_dict dictionary to set items in
Definition at line 218 of file command_builder.py.
Referenced by wrappers.mode_wrapper.MODEWrapper.add_merge_config_file(), wrappers.point_stat_wrapper.PointStatWrapper.create_c_dict(), and wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.create_c_dict().
set_c_dict_list()
def wrappers.command_builder.CommandBuilder.set_c_dict_list (self, c_dict, mp_config_name, met_config_name, c_dict_key = None, remove_quotes = False)
Get list from METplus configuration file and format it to be passed into a MET configuration file.
Set c_dict item with formatted string. Args:
Parameters
c_dict configuration dictionary to set
mp_config_name METplus configuration variable name. Assumed to be in the [config] section. Value can be a comma-separated list of items.
met_config_name name of MET configuration variable to set. Also used to determine the key in c_dict to set (upper-case)
c_dict_key optional argument to specify c_dict key to store result. If set to None (default) then use upper-case of met_config_name
Definition at line 1106 of file command_builder.py.
set_c_dict_number()
def wrappers.command_builder.CommandBuilder.set_c_dict_number (self, c_dict, num_type, mp_config_name, met_config_name, c_dict_key = None)
Get integer from METplus configuration file and format it to be passed into a MET configuration file.
Set c_dict item with formatted string. Args:
Parameters
c_dict configuration dictionary to set
num_type type of number to get from config. If set to 'int', call getint function. If not, call getfloat function.
mp_config_name METplus configuration variable name. Assumed to be in the [config] section. Value can be a comma-separated list of items.
met_config_name name of MET configuration variable to set. Also used to determine the key in c_dict to set (upper-case) if c_dict_key is None
c_dict_key optional argument to specify c_dict key to store result. If set to None (default) then use upper-case of met_config_name
Definition at line 1154 of file command_builder.py.
Referenced by wrappers.command_builder.CommandBuilder.set_c_dict_number().
set_c_dict_string()
def wrappers.command_builder.CommandBuilder.set_c_dict_string (self, c_dict, mp_config_name, met_config_name, c_dict_key = None)
Get string from METplus configuration file and format it to be passed into a MET configuration file.
Set c_dict item with formatted string. Args:
Parameters
c_dict configuration dictionary to set
mp_config_name METplus configuration variable name. Assumed to be in the [config] section. Value can be a comma-separated list of items.
met_config_name name of MET configuration variable to set. Also used to determine the key in c_dict to set (upper-case)
c_dict_key optional argument to specify c_dict key to store result. If set to None (default) then use upper-case of met_config_name
Definition at line 1132 of file command_builder.py.
set_current_field_config()
def wrappers.command_builder.CommandBuilder.set_current_field_config (self, field_info = None)
Sets config variables for current fcst/obs name/level that can be referenced by other config variables such as OUTPUT_PREFIX.
Only sets then if CURRENT_VAR_INFO is set in c_dict. Args:
Parameters
field_info optional dictionary containing field information. If not provided, use [config] CURRENT_VAR_INFO
Definition at line 782 of file command_builder.py.
Referenced by wrappers.compare_gridded_wrapper.CompareGriddedWrapper.process_fields().
set_environment_variables()
def wrappers.command_builder.CommandBuilder.set_environment_variables (self, time_info = None)
Set environment variables that will be read set when running this tool.
This tool does not have a config file, but environment variables may still need to be set, such as MET_TMP_DIR and MET_PYTHON_EXE. Reformat as needed. Print list of variables that were set and their values. Args:
Parameters
time_info dictionary containing timing info from current run
Definition at line 107 of file command_builder.py.
Referenced by wrappers.make_plots_wrapper.MakePlotsWrapper.create_c_dict(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation(), wrappers.compare_gridded_wrapper.CompareGriddedWrapper.process_fields(), wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.process_fields(), wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh(), wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper.run_at_time(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string(), wrappers.grid_diag_wrapper.GridDiagWrapper.run_at_time_once(), wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once(), and wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/command_builder.py