METplus: wrappers.tc_gen_wrapper.TCGenWrapper Class Reference
wrappers.tc_gen_wrapper.TCGenWrapper Class Reference
Detailed Description
Definition at line 28 of file tc_gen_wrapper.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
def get_filter_values (self)
find all TC_GEN_FILTER_<n> values in the config files
def set_environment_variables (self, time_info)
Set environment variables that will be read by the MET config file.
def get_command (self)
def run_all_times (self)
Runs the MET application for a given run time.
def run_at_time (self, input_dict)
Process runtime and try to build command to run ascii2nc Args:
def run_at_time_once (self, time_info)
Process runtime and try to build command to run ascii2nc Args:
def find_input_files (self, time_info)
Get track and genesis files and set c_dict items.
def set_command_line_arguments (self, time_info)
Public Attributes
app_name
app_path
Member Function Documentation
find_input_files()
def wrappers.tc_gen_wrapper.TCGenWrapper.find_input_files (self, time_info)
Get track and genesis files and set c_dict items.
Also format forecast lead sequence to be read by the MET configuration file and set c_dict. Args:
Parameters
time_info time dictionary to use for string substitution
Returns
True if all inputs were found, False if not.
Definition at line 300 of file tc_gen_wrapper.py.
Referenced by wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), and wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once().
run_all_times()
def wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times (self)
Runs the MET application for a given run time.
This function loops over the list of forecast leads and runs the application for each. Args:
Parameters
input_dict dictionary containing timing information
Definition at line 250 of file tc_gen_wrapper.py.
run_at_time()
def wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time (self, input_dict)
Process runtime and try to build command to run ascii2nc Args:
Parameters
input_dict dictionary containing timing information
Definition at line 260 of file tc_gen_wrapper.py.
Referenced by wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), and wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times().
run_at_time_once()
def wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once (self, time_info)
Process runtime and try to build command to run ascii2nc Args:
Parameters
time_info dictionary containing timing information
Definition at line 278 of file tc_gen_wrapper.py.
Referenced by wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time(), and wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time().
set_environment_variables()
def wrappers.tc_gen_wrapper.TCGenWrapper.set_environment_variables (self, time_info)
Set environment variables that will be read by the MET config file.
Reformat as needed. Print list of variables that were set and their values. Args:
Parameters
time_info dictionary containing timing info from current run
Definition at line 167 of file tc_gen_wrapper.py.
Referenced by wrappers.make_plots_wrapper.MakePlotsWrapper.create_c_dict(), wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper.run_at_time(), wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), wrappers.tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string(), wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once(), and wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/tc_gen_wrapper.py