METplus: metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper Class Reference
metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper Class Reference
A Python class than encapsulates the plot_tcmpr.R plotting script.
Detailed Description
A Python class than encapsulates the plot_tcmpr.R plotting script.
Generates plots for input files with .tcst format and creates output subdirectory based on the input tcst file. The plot_tcmpr.R plot also supports additional filtering by calling MET tool tc_stat. This wrapper extends plot_tcmpr.R by allowing the user to specify as input a directory (to support plotting all files in the specified directory and its subdirectories). The user can now either indicate a file or directory in the (required) -lookin option.
Definition at line 29 of file tcmpr_plotter_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
Constructor for TCMPRPlotterWrapper Args:
def run_all_times (self)
Builds the command for invoking tcmpr.R plot script.
def create_output_subdir (self, tcst_file)
Extract the base portion of the tcst filename: eg amlqYYYYMMDDhh.gfso.nnnn in /d1/username/tc_pairs/YYYYMM/amlqYYYYMMDDhh.gfso.nnnn and use this as the subdirectory (gets appended to the TCMPR output directory).
def retrieve_optionals (self)
def get_command (self)
Over-ride CommandBuilder's get_command because unlike other MET tools, tcmpr_plotter_wrapper handles input files differently because it wraps an R-script, plot_tcmpr.R rather than a typical MET tool.
def build (self)
Override CommandBuilder's build() since the plot_tcmpr.R plot is set up differently from the other MET tools.
Public Attributes
app_name
input_data
plot_config_file
output_base_dir
prefix
title
subtitle
xlab
ylab
xlim
ylim
filter
filtered_tcst_data
dep_vars
scatter_x
scatter_y
skill_ref
series
series_ci
legend
lead
plot_types
rp_diff
demo_year
hfip_baseline
footnote_flag
plot_config_options
save_data
no_ee
no_log
save
tcmpr_script
Constructor & Destructor Documentation
__init__()
def metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.__init__ (self, config, instance = None, config_overrides = {})
Constructor for TCMPRPlotterWrapper Args:
Parameters
p The configuration instance, contains the conf file information.
logger A logger, can be None
Definition at line 41 of file tcmpr_plotter_wrapper.py.
Member Function Documentation
build()
def metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.build (self)
Override CommandBuilder's build() since the plot_tcmpr.R plot is set up differently from the other MET tools.
Definition at line 386 of file tcmpr_plotter_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.build_and_run_series_request(), metplus.wrappers.make_plots_wrapper.MakePlotsWrapper.create_c_dict(), metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data(), metplus.wrappers.compare_gridded_wrapper.CompareGriddedWrapper.process_fields(), metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.process_fields(), metplus.wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh(), metplus.wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), metplus.wrappers.tc_stat_wrapper.TCStatWrapper.run_at_time(), metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), metplus.wrappers.user_script_wrapper.UserScriptWrapper.run_at_time_once(), metplus.wrappers.gempak_to_cf_wrapper.GempakToCFWrapper.run_at_time_once(), metplus.wrappers.grid_diag_wrapper.GridDiagWrapper.run_at_time_once(), metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time_once(), metplus.wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), metplus.wrappers.ascii2nc_wrapper.ASCII2NCWrapper.run_at_time_once(), metplus.wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_for_all_fields(), metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_per_field(), and metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
create_output_subdir()
def metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.create_output_subdir (self, tcst_file)
Extract the base portion of the tcst filename: eg amlqYYYYMMDDhh.gfso.nnnn in /d1/username/tc_pairs/YYYYMM/amlqYYYYMMDDhh.gfso.nnnn and use this as the subdirectory (gets appended to the TCMPR output directory).
This allows the user to determine which plots correspond to the input track file.
Args:
Parameters
tcst_file The input tc-pairs file. Returns: dated_output_dir: The output dir where the final tcmpr plots will be saved
Definition at line 276 of file tcmpr_plotter_wrapper.py.
get_command()
def metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.get_command (self)
Over-ride CommandBuilder's get_command because unlike other MET tools, tcmpr_plotter_wrapper handles input files differently because it wraps an R-script, plot_tcmpr.R rather than a typical MET tool.
Build command to run from arguments
Definition at line 377 of file tcmpr_plotter_wrapper.py.
Referenced by metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.build(), and metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once().
retrieve_optionals()
def metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.retrieve_optionals (self)
Creates a dictionary of the options and their values.
   Args:
   Returns:
       options_dict: a dictionary of the values to the optional args
          in a format where the argument is the key, and
          the args value is the dictionary value.  This is
          useful in keeping the args separate from their
          values, where values with whitespaces aren't
          compromised (i.e. whitespaces are retained).
Definition at line 300 of file tcmpr_plotter_wrapper.py.
Referenced by metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.run_all_times().
run_all_times()
def metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.run_all_times (self)
Builds the command for invoking tcmpr.R plot script.
Args:
Returns:
Definition at line 143 of file tcmpr_plotter_wrapper.py.
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/METplus/metplus/wrappers/tcmpr_plotter_wrapper.py