METplus: wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper Class Reference
wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper Class Reference
Detailed Description
Definition at line 26 of file gen_vx_mask_wrapper.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
def get_command (self)
def run_at_time (self, input_dict)
Runs the MET application for a given run time.
def run_at_time_all (self, time_info)
Loop over list of mask templates and call GenVxMask for each, adding the corresponding command line arguments for each call Args:
def find_input_files (self, time_info, temp_file)
Handle setting of input file list.
Public Attributes
app_name
app_path
isOK
args
Member Function Documentation
find_input_files()
def wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.find_input_files (self, time_info, temp_file)
Handle setting of input file list.
Args:
Parameters
time_info time dictionary for current runtime
temp_file path to temporary file used for previous run or empty string on first iteration
Returns
True if successfully found all inputs, False if not
Definition at line 206 of file gen_vx_mask_wrapper.py.
Referenced by wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_at_time(), wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), wrappers.grid_diag_wrapper.GridDiagWrapper.run_at_time_once(), wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), and wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once().
run_at_time()
def wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time (self, input_dict)
Runs the MET application for a given run time.
This function loops over the list of forecast leads and runs the application for each. Args:
Parameters
input_dict dictionary containing timing information
Returns
None
Definition at line 134 of file gen_vx_mask_wrapper.py.
Referenced by wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_all_times(), and wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times().
run_at_time_all()
def wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all (self, time_info)
Loop over list of mask templates and call GenVxMask for each, adding the corresponding command line arguments for each call Args:
Parameters
time_info time dictionary for current runtime
Returns
None
Definition at line 161 of file gen_vx_mask_wrapper.py.
Referenced by wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time().
The documentation for this class was generated from the following file:
/home/mccabe/metplus-doc/METplus.jprestop/metplus/wrappers/gen_vx_mask_wrapper.py