METplus: metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper Class Reference
metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper Class Reference
Wraps the MET tool regrid_data_plane to reformat gridded datasets.
Detailed Description
Wraps the MET tool regrid_data_plane to reformat gridded datasets.
Definition at line 25 of file regrid_data_plane_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def create_c_dict (self)
def get_explicit_field_names (self, index, data_type, time_info)
Get output field name from [FCST/OBS]_<APP_NAME>_* Use input/output field name if it exists, then use generic field name, then return empty string if neither are set Args:
def get_input_indices (self, data_type)
Find all n in [FCST/OBS]_REGRID_DATA_PLANE_VAR<n>_INPUT_FIELD_NAME or [FCST/OBS]_REGRID_DATA_PLANE_VAR<n>_FIELD_NAME.
def get_field_info_list (self, var_list, data_type, time_info)
Read field list (var_list) generated from [FCST/OBS]_VAR<n>_ variables replace values from [FCST/OBS]_REGRID_DATA_PLANE_VAR<n>_INPUT_ variables if they are set Args:
def get_output_name (self, field_info, data_type, input_name)
Set output name if set in field info or use input name if not Args:
def handle_output_file (self, time_info, field_info, data_type)
Add field level to time_info dict so it can be referenced in filename template, then set output file path and check if it should be skipped if it exists.
def run_once_per_field (self, time_info, field_info_list, data_type)
Loop over fields and run command for each.
def run_once_for_all_fields (self, time_info, field_info_list, data_type)
Loop over fields to add each field info, then run command once to process all fields.
def run_at_time_once (self, time_info, var_list, data_type)
Build command or commands to run at the given run time Args:
def find_input_files (self, time_info, data_type, field_info_list)
Get input file and verification grid to process.
def set_command_line_arguments (self)
Returns False if command should not be run.
def set_field_command_line_arguments (self, field_info, data_type)
Sets command line arguments for an input field.
Public Attributes
app_name
app_path
isOK
Member Function Documentation
find_input_files()
def metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.find_input_files (self, time_info, data_type, field_info_list)
Get input file and verification grid to process.
Use the first field in the list to substitute level if that is provided in the filename template
Definition at line 444 of file regrid_data_plane_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.get_files_from_time(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), and metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once().
get_explicit_field_names()
def metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.get_explicit_field_names (self, index, data_type, time_info)
Get output field name from [FCST/OBS]_<APP_NAME>_* Use input/output field name if it exists, then use generic field name, then return empty string if neither are set Args:
Parameters
index integer n corresponding to [FCST/OBS]_VAR<n>_*
data_type type of data being processed (FCST or OBS)
Returns
tuple containing input and output field names to use
Definition at line 156 of file regrid_data_plane_wrapper.py.
Referenced by metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.get_field_info_list().
get_field_info_list()
def metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.get_field_info_list (self, var_list, data_type, time_info)
Read field list (var_list) generated from [FCST/OBS]_VAR<n>_ variables replace values from [FCST/OBS]_REGRID_DATA_PLANE_VAR<n>_INPUT_ variables if they are set Args:
Parameters
var_list list of field info objects populated from [FCST/OBS]_VAR<n>_ variables
data_type type of data to process, i.e. FCST or OBS
Returns
field list values combined with wrapper specific info
Definition at line 223 of file regrid_data_plane_wrapper.py.
Referenced by metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once().
get_input_indices()
def metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.get_input_indices (self, data_type)
Find all n in [FCST/OBS]_REGRID_DATA_PLANE_VAR<n>_INPUT_FIELD_NAME or [FCST/OBS]_REGRID_DATA_PLANE_VAR<n>_FIELD_NAME.
Used to see if there are any fields defined that don't correspond to an item in [FCST/OBS]_VAR<n>_ variables. Args:
Parameters
data_type type of field to look for (FCST or OBS)
Returns
list of indices that are set
Definition at line 202 of file regrid_data_plane_wrapper.py.
Referenced by metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.get_field_info_list().
get_output_name()
def metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.get_output_name (self, field_info, data_type, input_name)
Set output name if set in field info or use input name if not Args:
Parameters
field_info field dictionary to read level information
data_type type of data to process, i.e. FCST or OBS
input_name name of input field to be used as output name not explicitly set
Returns
output name
Definition at line 297 of file regrid_data_plane_wrapper.py.
Referenced by metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_for_all_fields(), and metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_per_field().
handle_output_file()
def metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.handle_output_file (self, time_info, field_info, data_type)
Add field level to time_info dict so it can be referenced in filename template, then set output file path and check if it should be skipped if it exists.
Args:
Parameters
time_info time dictionary used for string substitution
field_info field dictionary to read level information
data_type type of data to process, i.e. FCST or OBS
Returns
True if command should be run, False if it should not be run
Definition at line 316 of file regrid_data_plane_wrapper.py.
Referenced by metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_for_all_fields(), and metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_per_field().
run_at_time_once()
def metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once (self, time_info, var_list, data_type)
Build command or commands to run at the given run time Args:
Parameters
time_info time dictionary used for string substitution
var_list list of field dictionaries to process
data_type type of data to process, i.e. FCST or OBS
Definition at line 412 of file regrid_data_plane_wrapper.py.
Referenced by metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.run_all_times_custom(), metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.run_at_time(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time(), metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time(), and metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_once_per_lead().
run_once_for_all_fields()
def metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_for_all_fields (self, time_info, field_info_list, data_type)
Loop over fields to add each field info, then run command once to process all fields.
Args:
Parameters
time_info time dictionary used for string substitution
field_info_list list of field dictionaries to process
data_type type of data to process, i.e. FCST or OBS
Definition at line 371 of file regrid_data_plane_wrapper.py.
Referenced by metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once().
run_once_per_field()
def metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_per_field (self, time_info, field_info_list, data_type)
Loop over fields and run command for each.
Args:
Parameters
time_info time dictionary used for string substitution
field_info_list list of field dictionaries to process
data_type type of data to process, i.e. FCST or OBS
Definition at line 330 of file regrid_data_plane_wrapper.py.
Referenced by metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once().
set_field_command_line_arguments()
def metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.set_field_command_line_arguments (self, field_info, data_type)
Sets command line arguments for an input field.
Args:
Parameters
field_info field dictionary to read level information
data_type type of data to process, i.e. FCST or OBS
Returns
input name to be used as output name if not explicitly set
Definition at line 479 of file regrid_data_plane_wrapper.py.
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/release-4.0.0-beta3/METplus/metplus/wrappers/regrid_data_plane_wrapper.py