METplus: metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper Class Reference
metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper Class Reference
Detailed Description
Definition at line 26 of file plot_data_plane_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def create_c_dict (self)
def get_command (self)
def run_at_time (self, input_dict)
Runs the MET application for a given run time.
def run_at_time_once (self, time_info)
Process runtime and try to build command to run ascii2nc Args:
def find_input_files (self, time_info)
def set_command_line_arguments (self, time_info)
def convert_to_png (self, ps_filename)
Convert output postscript file to a rotated png image file.
Public Attributes
app_name
app_path
Member Function Documentation
convert_to_png()
def metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.convert_to_png (self, ps_filename)
Convert output postscript file to a rotated png image file.
Parameters
ps_filename ps file generated by plot_data_plane
Returns
True if success, False if error
Definition at line 214 of file plot_data_plane_wrapper.py.
Referenced by metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time_once().
run_at_time()
def metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time (self, input_dict)
Runs the MET application for a given run time.
This function loops over the list of forecast leads and runs the application for each. Args:
Parameters
input_dict dictionary containing timing information
Definition at line 113 of file plot_data_plane_wrapper.py.
Referenced by metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), and metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times().
run_at_time_once()
def metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time_once (self, time_info)
Process runtime and try to build command to run ascii2nc Args:
Parameters
time_info dictionary containing timing information
Definition at line 140 of file plot_data_plane_wrapper.py.
Referenced by metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.run_all_times_custom(), metplus.wrappers.reformat_gridded_wrapper.ReformatGriddedWrapper.run_at_time(), metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time(), metplus.wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time(), metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.run_at_time(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time(), metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time(), and metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.run_once_per_lead().
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/METplus/metplus/wrappers/plot_data_plane_wrapper.py