METplus: metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper Class Reference
metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper Class Reference
Wraps the MET tool ensemble_stat to compare ensemble datasets.
Detailed Description
Wraps the MET tool ensemble_stat to compare ensemble datasets.
Definition at line 25 of file ensemble_stat_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def create_c_dict (self)
Create a dictionary containing the values set in the config file that are required for running ensemble stat.
def format_met_config_type (self, c_dict, key_prefix)
Format type item for MET config.
def run_at_time_all_fields (self, time_info)
Runs the MET application for a given time and forecast lead combination Args:
def get_all_field_info (self, var_list, data_type)
Get field info based on data type.
def find_model_members (self, time_info)
Finds the model member files to compare Args:
def set_environment_variables (self, fcst_field, obs_field, ens_field, time_info)
def process_fields (self, time_info, fcst_field, obs_field, ens_field=None)
Set and print environment variables, then build/run MET command Args:
def clear (self)
Unset class variables to prepare for next run time.
def get_command (self)
Builds the command to run the MET application string.
Public Attributes
app_name
app_path
param
point_obs_files
grid_obs_files
outdir
Static Public Attributes
list OUTPUT_FLAGS
list ENSEMBLE_FLAGS
Member Function Documentation
create_c_dict()
def metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.create_c_dict (self)
Create a dictionary containing the values set in the config file that are required for running ensemble stat.
This will make it easier for unit testing.
Returns:
Returns
A dictionary of the ensemble stat values from the config file.
Definition at line 60 of file ensemble_stat_wrapper.py.
find_model_members()
def metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.find_model_members (self, time_info)
Finds the model member files to compare Args:
Parameters
time_info dictionary containing timing information string
Returns
Returns a list of the paths to the ensemble model files
Definition at line 485 of file ensemble_stat_wrapper.py.
Referenced by metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.run_at_time_all_fields().
format_met_config_type()
def metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.format_met_config_type (self, c_dict, key_prefix)
Format type item for MET config.
Parameters
c_dict dictionary to check and add item if appropriate
key_prefix prefix to add to input keys to search in c_dict
Returns
formatted string "type = [{}];" or empty string if nothing is set
Definition at line 371 of file ensemble_stat_wrapper.py.
Referenced by metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.create_c_dict().
get_command()
def metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.get_command (self)
Builds the command to run the MET application string.
Returns
Returns a MET command with arguments that you can run
Definition at line 721 of file ensemble_stat_wrapper.py.
Referenced by metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.build(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data(), metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.process_fields(), metplus.wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), metplus.wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), metplus.wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_add_method(), metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_derive_method(), metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_subtract_method(), and metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_sum_method().
process_fields()
def metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.process_fields (self, time_info, fcst_field, obs_field, ens_field = None)
Set and print environment variables, then build/run MET command Args:
Parameters
time_info dictionary containing timing information
fcst_field field information formatted for MET config file
obs_field field information formatted for MET config file
Definition at line 684 of file ensemble_stat_wrapper.py.
Referenced by metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.run_at_time_all_fields().
run_at_time_all_fields()
def metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.run_at_time_all_fields (self, time_info)
Runs the MET application for a given time and forecast lead combination Args:
Parameters
time_info dictionary containing timing information
Definition at line 390 of file ensemble_stat_wrapper.py.
Member Data Documentation
ENSEMBLE_FLAGS
list metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.ENSEMBLE_FLAGS static
Initial value:
=  ['latlon',
                      'mean',
                      'stdev',
                      'minus',
                      'plus',
                      'min',
                      'max',
                      'range',
                      'vld_count',
                      'frequency',
                      'nep',
                      'nmep',
                      'rank',
                      'weight',
                      ]
Definition at line 36 of file ensemble_stat_wrapper.py.
Referenced by metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.create_c_dict(), and metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.find_model_members().
OUTPUT_FLAGS
list metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.OUTPUT_FLAGS static
Initial value:
=  ['ecnt',
                    'rps',
                    'rhist',
                    'phist',
                    'orank',
                    'ssvar',
                    'relp'
                    ]
Definition at line 28 of file ensemble_stat_wrapper.py.
Referenced by metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.create_c_dict(), and metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.find_model_members().
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/METplus/metplus/wrappers/ensemble_stat_wrapper.py