METplus: metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper Class Reference
metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper Class Reference
SeriesByLeadWrapper performs series analysis of paired data based on lead time and generates plots for each requested variable and statistic, as specified in a configuration/parameter file.
Detailed Description
SeriesByLeadWrapper performs series analysis of paired data based on lead time and generates plots for each requested variable and statistic, as specified in a configuration/parameter file.
Definition at line 29 of file series_by_lead_wrapper.py.
Public Member Functions
def __init__ (self, config)
def create_c_dict (self)
def get_lead_sequences (self)
def run_all_times (self)
Perform a series analysis of extra tropical cyclone paired data based on lead time (forecast hour) This requires invoking the MET run_series_analysis binary, followed by generating graphics that are recognized by the MET viewer using the plot_data_plane and converting to postscript.
def filter_with_tc_stat (self, tile_dir, init_times)
Perform optional filtering using MET tc_stat.
def perform_series_for_fhr_groups (self, tile_dir)
Series analysis for groups based on forecast hours.
def perform_series_for_all_fhrs (self, tile_dir)
Performs a series analysis by lead time, based on a range and increment of forecast hours.
def get_nseries (self, do_fhr_by_range, nc_var_file)
Determine the number of series for this lead time and its associated variable via calculating the max series_cnt_TOTAL value, maximum.
def get_netcdf_min_max (self, do_fhr_by_range, nc_var_files, cur_stat)
Determine the min and max for all lead times for each statistic and variable pairing.
def retrieve_nc_files (self, do_fhr_by_range)
Retrieve all the netCDF files created by MET series_analysis.
def retrieve_fhr_tiles (self, tile_list, type_regex)
Retrieves only the gridded tile files that correspond to the type.
def find_matching_tile (self, fcst_file, anly_tiles)
Find the corresponding ANLY 30x30 tile file to the fcst tile file.
def generate_plots (self, do_fhr_by_range)
Generate the plots and animation GIFs for the series analysis results.
def create_animated_gifs (self, do_fhr_by_range)
Creates the animated GIF files from the .png files created in generate_plots().
def apply_series_filters (self, tile_dir, init_times, series_output_dir, filter_opts, staging_dir)
Apply filter options, as specified in the param/config file.
Static Public Member Functions
def get_var_ncfiles (do_fhr_by_range, cur_var, nc_list)
Retrieve only the netCDF files corresponding to this statistic and variable pairing.
def get_anly_or_fcst_files (filedir, file_type, filename_regex, cur_fhr)
Get all the ANLY or FCST files by walking through the directories starting at filedir.
Public Attributes
app_name
do_fhr_by_group
fhr_group_labels
stat_list
plot_data_plane_exe
convert_exe
ncap2_exe
ncdump_exe
rm_exe
isOK
series_analysis_exe
input_dir
series_lead_filtered_out_dir
series_lead_out_dir
staging_dir
background_map
series_filter_opts
fcst_ascii_regex
anly_ascii_regex
series_anly_configuration_file
fcst_tile_regex
anly_tile_regex
Member Function Documentation
apply_series_filters()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.apply_series_filters (self, tile_dir, init_times, series_output_dir, filter_opts, staging_dir)
Apply filter options, as specified in the param/config file.
Args:
Parameters
tile_dir Directory where input data files reside. e.g. data which we will be applying our filter criteria.
init_times List of init times that define the input data.
series_output_dir The directory where the filter results will be stored.
filter_opts The filter options to apply
staging_dir The temporary directory where intermediate files are saved. Returns: None
Definition at line 1307 of file series_by_lead_wrapper.py.
Referenced by metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.create_animated_gifs(), and metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.filter_with_tc_stat().
create_animated_gifs()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.create_animated_gifs (self, do_fhr_by_range)
Creates the animated GIF files from the .png files created in generate_plots().
Args:
Parameters
do_fhr_by_range The boolean flag indicating whether series analysis was performed on the entire range (True) or on groups of forecast hours (False). Returns:
Definition at line 1215 of file series_by_lead_wrapper.py.
Referenced by metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times().
filter_with_tc_stat()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.filter_with_tc_stat (self, tile_dir, init_times)
Perform optional filtering using MET tc_stat.
Args:
Parameters
tile_dir The directory where the input data resides.
init_times A list of init times under which series filters will be applied. Returns: filter_tile_dir: A directory of the resulting files from applying the filter criteria (as specified in the param/ config file).
Definition at line 209 of file series_by_lead_wrapper.py.
Referenced by metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times().
find_matching_tile()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.find_matching_tile (self, fcst_file, anly_tiles)
Find the corresponding ANLY 30x30 tile file to the fcst tile file.
Args:
Parameters
fcst_file : The fcst file (full path) that is used to derive the corresponding analysis file name.
anly_tiles : The list of all available 30x30 analysis tiles.
Returns: anly_from_fcst (string): The name of the analysis tile file that corresponds to the same lead time as the input fcst tile.
Definition at line 963 of file series_by_lead_wrapper.py.
generate_plots()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.generate_plots (self, do_fhr_by_range)
Generate the plots and animation GIFs for the series analysis results.
Args:
Parameters
do_fhr_by_range The boolean flag which indicates whether series analysis is to be performed for the entire range of fhrs, (True), or by groups of fhrs (False).
Returns: None
Definition at line 1046 of file series_by_lead_wrapper.py.
Referenced by metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times().
get_anly_or_fcst_files()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.get_anly_or_fcst_files (filedir, file_type, filename_regex, cur_fhr) static
Get all the ANLY or FCST files by walking through the directories starting at filedir.
Args:
Parameters
filedir The topmost directory from which the search begins.
file_type FCST or ANLY
filename_regex The regular expression that defines the naming format of the files of interest.
cur_fhr The current forecast hour for which we need to find the corresponding file
Returns: file_paths (string): a list of filenames (with full filepath)
Definition at line 991 of file series_by_lead_wrapper.py.
Referenced by metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.find_matching_tile(), metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.perform_series_for_all_fhrs(), and metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.perform_series_for_fhr_groups().
get_netcdf_min_max()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.get_netcdf_min_max (self, do_fhr_by_range, nc_var_files, cur_stat)
Determine the min and max for all lead times for each statistic and variable pairing.
Args:
Parameters
do_fhr_by_range Boolean value indicating whether series analysis was performed on a range of forecast hours (True) or on a grouping of forecast hours (False).
nc_var_files A list of the netCDF files generated by the MET series analysis tool that correspond to the variable of interest.
cur_stat The current statistic of interest: ie. RMSE, MAE, ODEV, FDEV, ME, or TOTAL.
Returns: tuple (vmin, vmax) vmin: The minimum vmax: The maximum
Definition at line 687 of file series_by_lead_wrapper.py.
Referenced by metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.generate_plots().
get_nseries()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.get_nseries (self, do_fhr_by_range, nc_var_file)
Determine the number of series for this lead time and its associated variable via calculating the max series_cnt_TOTAL value, maximum.
Args:
Parameters
do_fhr_by_range Boolean value indicating whether series analysis was performed on a range of forecast hours (True) or on a "bucket" of forecast hours (False).
nc_var_file The netCDF file for a particular variable.
Returns: maximum (float): The maximum value of series_cnt_TOTAL of all the netCDF files for the variable cur_var. None: If no max value is found.
Definition at line 585 of file series_by_lead_wrapper.py.
Referenced by metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.generate_plots().
get_var_ncfiles()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.get_var_ncfiles (do_fhr_by_range, cur_var, nc_list) static
Retrieve only the netCDF files corresponding to this statistic and variable pairing.
Args:
Parameters
do_fhr_by_range The boolean value indicating whether series analysis was performed on a range of forecast hours (True), or on a group of forecast hours (False)
cur_var The variable of interest.
nc_list The list of all netCDF files that were generated by the MET utility series_analysis.
Returns: var_ncfiles: A list of netCDF files that correspond to this variable.
Definition at line 845 of file series_by_lead_wrapper.py.
Referenced by metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.generate_plots().
perform_series_for_all_fhrs()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.perform_series_for_all_fhrs (self, tile_dir)
Performs a series analysis by lead time, based on a range and increment of forecast hours.
Invokes the MET tool Series-analysis
Args:
Parameters
tile_dir The location of the input data (output from running ExtractTiles.py)
lead_seq List of forecast hours to process
Returns: None
Definition at line 434 of file series_by_lead_wrapper.py.
Referenced by metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times().
perform_series_for_fhr_groups()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.perform_series_for_fhr_groups (self, tile_dir)
Series analysis for groups based on forecast hours.
Args:
Parameters
tile_dir The location where input data resides. Returns: None
Definition at line 269 of file series_by_lead_wrapper.py.
Referenced by metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times().
retrieve_fhr_tiles()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.retrieve_fhr_tiles (self, tile_list, type_regex)
Retrieves only the gridded tile files that correspond to the type.
Args:
Parameters
tile_list List of tiles (full filepath).
type_regex The regex that corresponds to the tile filename for this type
Returns: fhr_tiles (string): A string of gridded tile names separated by newlines
Definition at line 930 of file series_by_lead_wrapper.py.
Referenced by metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.perform_series_for_all_fhrs().
retrieve_nc_files()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.retrieve_nc_files (self, do_fhr_by_range)
Retrieve all the netCDF files created by MET series_analysis.
Args:
Parameters
do_fhr_by_range Boolean value, True if series analysis was performed on range. False otherwise. Returns: nc_list: A list of the netCDF files (full path) created when the MET series analysis binary was invoked.
Definition at line 884 of file series_by_lead_wrapper.py.
Referenced by metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.generate_plots().
run_all_times()
def metplus.wrappers.series_by_lead_wrapper.SeriesByLeadWrapper.run_all_times (self)
Perform a series analysis of extra tropical cyclone paired data based on lead time (forecast hour) This requires invoking the MET run_series_analysis binary, followed by generating graphics that are recognized by the MET viewer using the plot_data_plane and converting to postscript.
A pre-requisite is the presence of the filter file and storm files (set to nxm degree tiles as indicated in the param/config file) the specified init and lead times.
Create the following command to satisfy MET series_analysis: series_analysis -fcst <FILTERED_OUT_DIR>/FCST_FILES_F<CUR_FHR> -obs <FILTERED_OUT_DIR>/ANLY_FILES_F<CUR_FHR> -out <OUT_DIR>/series_F<CURR_FHR_<NAME>_<LEVEL>.nc -config SeriesAnalysisConfig_by_lead Args:
Returns: None: Invokes MET series_analysis and any other MET tool to perform series analysis. Then plots are generated for the variables and statistics (as indicated in the param/config file) corresponding to each forecast lead time.
Definition at line 123 of file series_by_lead_wrapper.py.
The documentation for this class was generated from the following file:
/d1/personal/mccabe/release/METplus/metplus/wrappers/series_by_lead_wrapper.py