METplus: metplus.wrappers.command_builder.CommandBuilder Class Reference
metplus.wrappers.command_builder.CommandBuilder Class Reference
Common functionality to wrap all MET applications.
Detailed Description
Common functionality to wrap all MET applications.
Definition at line 34 of file command_builder.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def override_config (self, config_overrides)
def create_c_dict (self)
def clear (self)
Unset class variables to prepare for next run time.
def set_environment_variables (self, time_info=None)
Set environment variables that will be read set when running this tool.
def log_error (self, error_string)
def set_user_environment (self, time_info=None)
Set environment variables defined in [user_env_vars] section of config.
def print_all_envs (self, print_copyable=True)
Create list of log messages that output all environment variables that were set by this wrapper.
def handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
def handle_window_variables (self, c_dict, app_name, dtypes=['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
def set_output_path (self, outpath)
Split path into directory and filename then save both.
def get_output_path (self)
Combine output directory and filename then return result.
def add_env_var (self, key, name)
Sets an environment variable so that the MET application can reference it in the parameter file or the application itself.
def get_env_copy (self, var_list=None)
Print list of environment variables that can be easily copied into terminal.
def print_env_item (self, item)
Print single environment variable in the log file.
def handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default=None, sec='config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
def find_model (self, time_info, var_info=None, mandatory=True, return_list=False)
Finds the model file to compare Args:
def find_obs (self, time_info, var_info=None, mandatory=True, return_list=False)
Finds the observation file to compare Args:
def find_obs_offset (self, time_info, var_info=None, mandatory=True, return_list=False)
Finds the observation file to compare, looping through offset list until a file is found Args:
def find_data (self, time_info, var_info=None, data_type='', mandatory=True, return_list=False, allow_dir=False)
Finds the data file to compare Args:
def find_exact_file (self, level, data_type, time_info, mandatory=True, return_list=False, allow_dir=False)
def find_file_in_window (self, level, data_type, time_info, mandatory=True, return_list=False)
def write_list_file (self, filename, file_list, output_dir=None)
Writes a file containing a list of filenames to the staging dir.
def find_and_check_output_file (self, time_info=None, is_directory=False, output_path_template=None)
Build full path for expected output file and check if it exists.
def format_list_string (self, list_string)
Add quotation marks around each comma separated item in the string.
def check_for_externals (self)
def check_for_gempak (self)
def check_gempaktocf (self, gempaktocf_jar)
def add_field_info_to_time_info (self, time_info, field_info)
Add name and level values from field info to time info dict to be used in string substitution Args:
def set_current_field_config (self, field_info=None)
Sets config variables for current fcst/obs name/level that can be referenced by other config variables such as OUTPUT_PREFIX.
def check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
def get_field_info (self, d_type, v_name, v_level='', v_thresh=[], v_extra='')
Format field information into format expected by MET config file Args:
def get_verification_mask (self, time_info)
If verification mask template is set in the config file, use it to find the verification mask filename.
def get_command (self)
Builds the command to run the MET application string.
def build (self)
Build and run command.
def run_command (self, cmd)
Run a command with the appropriate environment.
def run_at_time (self, input_dict)
Used to output error and exit if wrapper is attemped to be run with LOOP_ORDER = times and the run_at_time method is not implemented.
def run_all_times (self)
Loop over time range specified in conf file and call METplus wrapper for each time.
def set_time_dict_for_single_runtime (self, c_dict)
def set_met_config_list (self, c_dict, mp_config_name, met_config_name, c_dict_key=None, remove_quotes=False, allow_empty=False)
Get list from METplus configuration file and format it to be passed into a MET configuration file.
def set_met_config_string (self, c_dict, mp_config_name, met_config_name, c_dict_key=None, remove_quotes=False)
Get string from METplus configuration file and format it to be passed into a MET configuration file.
def set_met_config_number (self, c_dict, num_type, mp_config_name, met_config_name, c_dict_key=None)
Get integer from METplus configuration file and format it to be passed into a MET configuration file.
def set_met_config_int (self, c_dict, mp_config_name, met_config_name, c_dict_key=None)
def set_met_config_float (self, c_dict, mp_config_name, met_config_name, c_dict_key=None)
def set_met_config_thresh (self, c_dict, mp_config_name, met_config_name, c_dict_key=None)
def set_met_config_bool (self, c_dict, mp_config_name, met_config_name, c_dict_key=None, uppercase=True)
Get boolean from METplus configuration file and format it to be passed into a MET configuration file.
def format_met_config_dictionary (self, name, keys)
Return formatted dictionary named <name> with any <items> if they are set to a value.
def handle_c_dict_regrid (self, c_dict, set_to_grid=True)
def get_regrid_dict (self)
def handle_description (self, c_dict)
Get description from config.
def get_output_prefix (self, time_info=None)
Read {APP_NAME}_OUTPUT_PREFIX from config.
def set_climo_env_vars (self)
Set all climatology environment variables from CLIMO_<item>_FILE c_dict values if they are not set to None.
def read_climo_wrapper_specific (self, met_tool, c_dict)
Read climatology directory and template values for specific MET tool specified and set the values in c_dict.
def handle_climo (self, time_info)
Substitute time information into all climatology template values.
def handle_climo_file_item (self, time_info, climo_item)
Handle a single climatology value by substituting time information, prepending input directory if provided, and preprocessing file if necessary.
def get_wrapper_or_generic_config (self, generic_config_name)
Check for config variable with <APP_NAME>_ prepended first.
Static Public Member Functions
def format_regrid_to_grid (to_grid)
def format_met_config_dict (c_dict, dict_name, item_list)
Build string containing dictionary from a MET configuration file with any items that were set in the user's METplus configuration.
Public Attributes
isOK
errors
config
logger
env_list
debug
args
input_dir
infiles
outdir
outfile
param
all_commands
instance
env
c_dict
cmdrunner
log_name
Static Public Attributes
list climo_types = ['MEAN', 'STDEV']
Member Function Documentation
add_field_info_to_time_info()
def metplus.wrappers.command_builder.CommandBuilder.add_field_info_to_time_info (self, time_info, field_info)
Add name and level values from field info to time info dict to be used in string substitution Args:
Parameters
time_info time dictionary to add items to
field_info field dictionary to get values from
Definition at line 864 of file command_builder.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.build_and_run_series_request(), metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.generate_plots(), metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_for_all_fields(), and metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_per_field().
check_for_python_embedding()
def metplus.wrappers.command_builder.CommandBuilder.check_for_python_embedding (self, input_type, var_info)
Check if field name of given input type is a python script.
If it is not, return the field name. If it is, check if the input datatype is a valid Python Embedding string, set the c_dict item that sets the file_type in the MET config file accordingly, and set the output string to 'python_embedding. Used to set up Python Embedding input for MET tools that support multiple input files, such as MTD, EnsembleStat, and SeriesAnalysis. Args:
Parameters
input_type type of field input, i.e. FCST, OBS, ENS, POINT_OBS, GRID_OBS, or BOTH
var_info dictionary item containing field information for the current *_VAR<n>_* configs being handled
Returns
field name if not a python script, 'python_embedding' if it is, and None if configuration is invalid
Definition at line 896 of file command_builder.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.check_python_embedding(), metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.get_all_field_info(), and metplus.wrappers.mtd_wrapper.MTDWrapper.run_at_time_loop_string().
find_and_check_output_file()
def metplus.wrappers.command_builder.CommandBuilder.find_and_check_output_file (self, time_info = None, is_directory = False, output_path_template = None)
Build full path for expected output file and check if it exists.
If output file doesn't exist or it does exists and we are not skipping it then return True to run the tool. Otherwise return False to not run the tool Args:
Parameters
time_info time dictionary to use to fill out output file template
is_directory If True, check in output directory for any files that match the pattern {app_name}_{output_prefix}*YYYYMMDD_HHMMSSV*
output_path_template optional filename template to use If None, build output path template from c_dict's OUTPUT_DIR and OUTPUT_TEMPLATE. Default is None
Returns
True if the app should be run or False if it should not
Definition at line 731 of file command_builder.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.build_and_run_series_request(), metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.create_output_directories(), metplus.wrappers.tc_stat_wrapper.TCStatWrapper.handle_jobs(), metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.handle_output_file(), metplus.wrappers.compare_gridded_wrapper.CompareGriddedWrapper.process_fields(), metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.process_fields(), metplus.wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh(), metplus.wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh(), metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), metplus.wrappers.gempak_to_cf_wrapper.GempakToCFWrapper.run_at_time_once(), metplus.wrappers.grid_diag_wrapper.GridDiagWrapper.run_at_time_once(), metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time_once(), metplus.wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), metplus.wrappers.ascii2nc_wrapper.ASCII2NCWrapper.run_at_time_once(), metplus.wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), and metplus.wrappers.command_builder.CommandBuilder.write_list_file().
find_data()
def metplus.wrappers.command_builder.CommandBuilder.find_data (self, time_info, var_info = None, data_type = '', mandatory = True, return_list = False, allow_dir = False)
Finds the data file to compare Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
data_type type of data to find (i.e. FCST_ or OBS_)
mandatory if True, report error if not found, warning if not default is True string
Returns
Returns the path to an observation file
Definition at line 450 of file command_builder.py.
Referenced by metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.find_input_files(), metplus.wrappers.grid_diag_wrapper.GridDiagWrapper.find_input_files(), metplus.wrappers.tc_gen_wrapper.TCGenWrapper.find_input_files(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.find_input_files(), metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.find_input_files(), metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.find_input_files(), metplus.wrappers.command_builder.CommandBuilder.find_model(), metplus.wrappers.command_builder.CommandBuilder.find_obs(), metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.run_at_time_all_fields(), and metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time_once().
find_model()
def metplus.wrappers.command_builder.CommandBuilder.find_model (self, time_info, var_info = None, mandatory = True, return_list = False)
Finds the model file to compare Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
mandatory if True, report error if not found, warning if not default is True string
Returns
Returns the path to an model file
Definition at line 375 of file command_builder.py.
Referenced by metplus.wrappers.compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_all_fields(), metplus.wrappers.mtd_wrapper.MTDWrapper.run_at_time_loop_string(), metplus.wrappers.mode_wrapper.MODEWrapper.run_at_time_one_field(), and metplus.wrappers.compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_one_field().
find_obs()
def metplus.wrappers.command_builder.CommandBuilder.find_obs (self, time_info, var_info = None, mandatory = True, return_list = False)
Finds the observation file to compare Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
mandatory if True, report error if not found, warning if not default is True string
Returns
Returns the path to an observation file
Definition at line 391 of file command_builder.py.
Referenced by metplus.wrappers.point2grid_wrapper.Point2GridWrapper.find_input_files(), metplus.wrappers.command_builder.CommandBuilder.find_obs_offset(), metplus.wrappers.mtd_wrapper.MTDWrapper.run_at_time_loop_string(), metplus.wrappers.ascii2nc_wrapper.ASCII2NCWrapper.run_at_time_once(), and metplus.wrappers.mode_wrapper.MODEWrapper.run_at_time_one_field().
find_obs_offset()
def metplus.wrappers.command_builder.CommandBuilder.find_obs_offset (self, time_info, var_info = None, mandatory = True, return_list = False)
Finds the observation file to compare, looping through offset list until a file is found Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
mandatory if True, report error if not found, warning if not default is True string
Returns
Returns tuple of the path to an observation file and the time_info object used to find the data so the value of offset can be preserved
Definition at line 407 of file command_builder.py.
Referenced by metplus.wrappers.pb2nc_wrapper.PB2NCWrapper.find_input_files(), metplus.wrappers.compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_all_fields(), and metplus.wrappers.compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_one_field().
format_met_config_dict()
def metplus.wrappers.command_builder.CommandBuilder.format_met_config_dict (c_dict, dict_name, item_list) static
Build string containing dictionary from a MET configuration file with any items that were set in the user's METplus configuration.
Any variables that were not set will not be included in the dictionary string. Args:
Parameters
c_dict dictionary to check for items
dict_name name of dictionary to create in all caps. This corresponds to the name of the METplus configuration variable and c_dict value. The lower-case name also matches the name of the MET dictionary item, i.e. FCST_GENESIS corresponds to METpluc configuration variables TC_GEN_FCST_GENESIS_VMAX_THRESH and TC_GEN_FCST_GENESIS_MSLP_THRESH and c_dict keys FCST_GENESIS_VMAX_THRESH and FCST_GENESIS_MSLP_THRESH and MET configuration dictionary fcst_genesis = {}.
item_list list of MET dictionary items that can be set, i.e. [VMAX_THRESH, MSLP_THRESH], which corresponds to vmax_thresh and mslp_thresh in the MET configuration dictionary specified with dict_name.
Returns
string of formatted MET dictionary or empty string if no relevant variables were set
Definition at line 1195 of file command_builder.py.
Referenced by metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.format_met_config_type(), and metplus.wrappers.tc_gen_wrapper.TCGenWrapper.set_environment_variables().
format_met_config_dictionary()
def metplus.wrappers.command_builder.CommandBuilder.format_met_config_dictionary (self, name, keys)
Return formatted dictionary named <name> with any <items> if they are set to a value.
If none of the items are set, return empty string
Parameters
name name of dictionary to create
keys list of c_dict keys to use if they are set
Returns
MET config formatted dictionary if any items are set, or empty string if not
Definition at line 1382 of file command_builder.py.
Referenced by metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.find_model_members(), and metplus.wrappers.command_builder.CommandBuilder.format_met_config_dictionary().
get_command()
def metplus.wrappers.command_builder.CommandBuilder.get_command (self)
Builds the command to run the MET application string.
Returns
Returns a MET command with arguments that you can run
Definition at line 1057 of file command_builder.py.
Referenced by metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.build(), metplus.wrappers.command_builder.CommandBuilder.build(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data(), metplus.wrappers.compare_gridded_wrapper.CompareGriddedWrapper.process_fields(), metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.process_fields(), metplus.wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), metplus.wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), metplus.wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_add_method(), metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_derive_method(), metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_subtract_method(), and metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.setup_sum_method().
get_field_info()
def metplus.wrappers.command_builder.CommandBuilder.get_field_info (self, d_type, v_name, v_level = '', v_thresh = [], v_extra = '')
Format field information into format expected by MET config file Args:
Parameters
v_level level of data to extract
v_thresh threshold value to use in comparison
v_name name of field to process
v_extra additional field information to add if available
d_type type of data to find i.e. FCST or OBS string
Returns
Returns formatted field information
Definition at line 927 of file command_builder.py.
Referenced by metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.get_all_field_info(), metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.get_formatted_fields(), metplus.wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh(), metplus.wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh(), metplus.wrappers.compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_all_fields(), metplus.wrappers.compare_gridded_wrapper.CompareGriddedWrapper.run_at_time_one_field(), metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_for_all_fields(), metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_once_per_field(), metplus.wrappers.grid_diag_wrapper.GridDiagWrapper.set_data_field(), and metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.set_data_field().
get_output_prefix()
def metplus.wrappers.command_builder.CommandBuilder.get_output_prefix (self, time_info = None)
Read {APP_NAME}_OUTPUT_PREFIX from config.
If time_info is set substitute values into filename template tags.
@param time_info (Optional) dictionary containing time info
@returns output prefix with values substituted if requested
Definition at line 1476 of file command_builder.py.
Referenced by metplus.wrappers.mode_wrapper.MODEWrapper.add_merge_config_file(), metplus.wrappers.command_builder.CommandBuilder.find_and_check_output_file(), metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.find_model_members(), metplus.wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh(), metplus.wrappers.grid_stat_wrapper.GridStatWrapper.set_environment_variables(), and metplus.wrappers.point_stat_wrapper.PointStatWrapper.set_environment_variables().
get_wrapper_or_generic_config()
def metplus.wrappers.command_builder.CommandBuilder.get_wrapper_or_generic_config (self, generic_config_name)
Check for config variable with <APP_NAME>_ prepended first.
If set use that value. If not, check for config without prefix.
Parameters
generic_config_name name of variable to read from config
Returns
value if set or empty string if not
Definition at line 1555 of file command_builder.py.
Referenced by metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.create_c_dict().
handle_climo_file_item()
def metplus.wrappers.command_builder.CommandBuilder.handle_climo_file_item (self, time_info, climo_item)
Handle a single climatology value by substituting time information, prepending input directory if provided, and preprocessing file if necessary.
All information is read from c_dict. CLIMO_<item>_FILE in c_dict is set.
Definition at line 1529 of file command_builder.py.
Referenced by metplus.wrappers.command_builder.CommandBuilder.handle_climo().
handle_description()
def metplus.wrappers.command_builder.CommandBuilder.handle_description (self, c_dict)
Get description from config.
If <app_name>_DESC is set, use that value. If not, check for DESC and use that if it is set. If set, set the DESC c_dict key to "desc = <value>;"
Parameters
c_dict dictionary to set value
Definition at line 1451 of file command_builder.py.
Referenced by metplus.wrappers.compare_gridded_wrapper.CompareGriddedWrapper.create_c_dict(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.create_c_dict(), and metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.create_c_dict().
handle_fcst_and_obs_field()
def metplus.wrappers.command_builder.CommandBuilder.handle_fcst_and_obs_field (self, gen_name, fcst_name, obs_name, default = None, sec = 'config')
Handles config variables that have fcst/obs versions or a generic variable to handle both, i.e.
FCST_NAME, OBS_NAME, and NAME. If FCST_NAME and OBS_NAME both exist, they are used. If both are don't exist, NAME is used.
Definition at line 330 of file command_builder.py.
Referenced by metplus.wrappers.mode_wrapper.MODEWrapper.add_merge_config_file().
handle_window_once()
def metplus.wrappers.command_builder.CommandBuilder.handle_window_once (self, c_dict, dtype, edge, app_name)
Check and set window dictionary variables like OBS_WINDOW_BEG or FCST_FILE_WINDW_END Args:
Parameters
c_dict dictionary to set items in
dtype type of data 'FCST' or 'OBS'
edge either 'BEGIN' or 'END'
Definition at line 218 of file command_builder.py.
Referenced by metplus.wrappers.command_builder.CommandBuilder.handle_window_variables().
handle_window_variables()
def metplus.wrappers.command_builder.CommandBuilder.handle_window_variables (self, c_dict, app_name, dtypes = ['FCST', OBS)
Handle all window config variables like [FCST/OBS]_<app_name>_WINDOW_[BEGIN/END] and [FCST/OBS]_<app_name>_FILE_WINDOW_[BEGIN/END] Args:
Parameters
c_dict dictionary to set items in
Definition at line 265 of file command_builder.py.
Referenced by metplus.wrappers.mode_wrapper.MODEWrapper.add_merge_config_file(), metplus.wrappers.point_stat_wrapper.PointStatWrapper.create_c_dict(), metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.create_c_dict(), and metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.create_c_dict().
print_all_envs()
def metplus.wrappers.command_builder.CommandBuilder.print_all_envs (self, print_copyable = True)
Create list of log messages that output all environment variables that were set by this wrapper.
Parameters
print_copyable if True, also output a list of shell commands that can be easily copied and pasted into a browser to recreate the environment that was set when the command was run
Returns
list of log messages
Definition at line 199 of file command_builder.py.
Referenced by metplus.wrappers.command_builder.CommandBuilder.run_command(), and metplus.wrappers.command_builder.CommandBuilder.set_environment_variables().
run_command()
def metplus.wrappers.command_builder.CommandBuilder.run_command (self, cmd)
Run a command with the appropriate environment.
Add command to list of all commands run.
Parameters
cmd command to run
Returns
True on success, False otherwise
Definition at line 1117 of file command_builder.py.
Referenced by metplus.wrappers.command_builder.CommandBuilder.build(), metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.convert_to_png(), and metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.generate_animations().
set_current_field_config()
def metplus.wrappers.command_builder.CommandBuilder.set_current_field_config (self, field_info = None)
Sets config variables for current fcst/obs name/level that can be referenced by other config variables such as OUTPUT_PREFIX.
Only sets then if CURRENT_VAR_INFO is set in c_dict. Args:
Parameters
field_info optional dictionary containing field information. If not provided, use [config] CURRENT_VAR_INFO
Definition at line 874 of file command_builder.py.
Referenced by metplus.wrappers.compare_gridded_wrapper.CompareGriddedWrapper.process_fields(), metplus.wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh(), and metplus.wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh().
set_environment_variables()
def metplus.wrappers.command_builder.CommandBuilder.set_environment_variables (self, time_info = None)
Set environment variables that will be read set when running this tool.
This tool does not have a config file, but environment variables may still need to be set, such as MET_TMP_DIR and MET_PYTHON_EXE. Reformat as needed. Print list of variables that were set and their values. Args:
Parameters
time_info dictionary containing timing info from current run
Definition at line 150 of file command_builder.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.build_and_run_series_request(), metplus.wrappers.make_plots_wrapper.MakePlotsWrapper.create_c_dict(), metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation(), metplus.wrappers.compare_gridded_wrapper.CompareGriddedWrapper.process_fields(), metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.process_fields(), metplus.wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh(), metplus.wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), metplus.wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper.run_at_time(), metplus.wrappers.tc_stat_wrapper.TCStatWrapper.run_at_time(), metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_at_time_loop_string(), metplus.wrappers.user_script_wrapper.UserScriptWrapper.run_at_time_once(), metplus.wrappers.grid_diag_wrapper.GridDiagWrapper.run_at_time_once(), metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time_once(), metplus.wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), metplus.wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once(), and metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
set_met_config_bool()
def metplus.wrappers.command_builder.CommandBuilder.set_met_config_bool (self, c_dict, mp_config_name, met_config_name, c_dict_key = None, uppercase = True)
Get boolean from METplus configuration file and format it to be passed into a MET configuration file.
Set c_dict item with boolean value expressed as a string. Args:
Parameters
c_dict configuration dictionary to set
mp_config_name METplus configuration variable name. Assumed to be in the [config] section.
met_config_name name of MET configuration variable to set. Also used to determine the key in c_dict to set (upper-case)
c_dict_key optional argument to specify c_dict key to store result. If set to None (default) then use upper-case of met_config_name
uppercase If true, set value to TRUE or FALSE
Definition at line 1345 of file command_builder.py.
Referenced by metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.create_c_dict(), metplus.wrappers.tc_stat_wrapper.TCStatWrapper.set_met_config_for_environment_variables(), and metplus.wrappers.command_builder.CommandBuilder.set_met_config_number().
set_met_config_list()
def metplus.wrappers.command_builder.CommandBuilder.set_met_config_list (self, c_dict, mp_config_name, met_config_name, c_dict_key = None, remove_quotes = False, allow_empty = False)
Get list from METplus configuration file and format it to be passed into a MET configuration file.
Set c_dict item with formatted string. Args:
Parameters
c_dict configuration dictionary to set
mp_config_name METplus configuration variable name. Assumed to be in the [config] section. Value can be a comma-separated list of items.
met_config_name name of MET configuration variable to set. Also used to determine the key in c_dict to set (upper-case)
c_dict_key optional argument to specify c_dict key to store result. If set to None (default) then use upper-case of met_config_name
allow_empty if True, if METplus config variable is set but is an empty string, then set the c_dict value to an empty list. If False, behavior is the same as when the variable is not set at all, which is to not set anything for the c_dict value
Definition at line 1231 of file command_builder.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.create_c_dict(), metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.create_c_dict(), metplus.wrappers.command_builder.CommandBuilder.format_met_config_dict(), and metplus.wrappers.tc_stat_wrapper.TCStatWrapper.set_met_config_for_environment_variables().
set_met_config_number()
def metplus.wrappers.command_builder.CommandBuilder.set_met_config_number (self, c_dict, num_type, mp_config_name, met_config_name, c_dict_key = None)
Get integer from METplus configuration file and format it to be passed into a MET configuration file.
Set c_dict item with formatted string. Args:
Parameters
c_dict configuration dictionary to set
num_type type of number to get from config. If set to 'int', call getint function. If not, call getfloat function.
mp_config_name METplus configuration variable name. Assumed to be in the [config] section. Value can be a comma-separated list of items.
met_config_name name of MET configuration variable to set. Also used to determine the key in c_dict to set (upper-case) if c_dict_key is None
c_dict_key optional argument to specify c_dict key to store result. If set to None (default) then use upper-case of met_config_name
Definition at line 1295 of file command_builder.py.
Referenced by metplus.wrappers.command_builder.CommandBuilder.set_met_config_number().
set_met_config_string()
def metplus.wrappers.command_builder.CommandBuilder.set_met_config_string (self, c_dict, mp_config_name, met_config_name, c_dict_key = None, remove_quotes = False)
Get string from METplus configuration file and format it to be passed into a MET configuration file.
Set c_dict item with formatted string. Args:
Parameters
c_dict configuration dictionary to set
mp_config_name METplus configuration variable name. Assumed to be in the [config] section. Value can be a comma-separated list of items.
met_config_name name of MET configuration variable to set. Also used to determine the key in c_dict to set (upper-case)
c_dict_key optional argument to specify c_dict key to store result. If set to None (default) then use upper-case of met_config_name
Definition at line 1269 of file command_builder.py.
Referenced by metplus.wrappers.compare_gridded_wrapper.CompareGriddedWrapper.create_c_dict(), metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.create_c_dict(), metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.create_c_dict(), metplus.wrappers.command_builder.CommandBuilder.format_met_config_dictionary(), metplus.wrappers.tc_stat_wrapper.TCStatWrapper.set_met_config_for_environment_variables(), and metplus.wrappers.command_builder.CommandBuilder.set_met_config_list().
write_list_file()
def metplus.wrappers.command_builder.CommandBuilder.write_list_file (self, filename, file_list, output_dir = None)
Writes a file containing a list of filenames to the staging dir.
Parameters
filename name of ascii file to write
file_list list of files to write to ascii file
output_dir (Optional) directory to write files. If None, ascii files are written to {STAGING_DIR}/file_lists
Returns
path to output file
Definition at line 700 of file command_builder.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.create_ascii_storm_files_list(), metplus.wrappers.tc_gen_wrapper.TCGenWrapper.find_input_files(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.find_input_files(), metplus.wrappers.ensemble_stat_wrapper.EnsembleStatWrapper.find_model_members(), metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.generate_animations(), metplus.wrappers.mtd_wrapper.MTDWrapper.run_at_time_loop_string(), and metplus.wrappers.grid_diag_wrapper.GridDiagWrapper.subset_input_files().
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/release-4.0.0-beta3/METplus/metplus/wrappers/command_builder.py