METplus: metplus.util.config_metplus.METplusConfig Class Reference
metplus.util.config_metplus.METplusConfig Class Reference
A replacement for the produtil.config.ProdConfig used throughout the METplus system.
Detailed Description
A replacement for the produtil.config.ProdConfig used throughout the METplus system.
You should never need to instantiate one of these — the launch() and load() functions do that for you. This class is the underlying implementation of most of the functionality described in launch() and load()
Definition at line 564 of file config_metplus.py.
Public Member Functions
def __init__ (self, conf=None)
Creates a new METplusConfig.
def log (self, sublog=None)
Overrides method in ProdConfig If the sublog argument is provided, then the logger will be under that subdomain of the "metplus" logging domain.
def move_all_to_config_section (self)
Move all configuration variables that are found in the previously supported sections into the config section.
def find_section (self, sec, opt)
Search through list of previously supported config sections to find variable requested.
def getraw (self, sec, opt, default='', count=0)
def check_default (self, sec, name, default)
helper function for get methods, report error and raise NoOptionError if default is not set.
def getexe (self, exe_name)
Wraps produtil exe with checks to see if option is set and if exe actually exists.
def getdir (self, dir_name, default=None, morevars=None, taskvars=None, must_exist=False)
Wraps produtil getdir and reports an error if it is set to /path/to.
def getdir_nocheck (self, dir_name, default=None)
def getstr_nocheck (self, sec, name, default=None)
def getstr (self, sec, name, default=None, badtypeok=False, morevars=None, taskvars=None)
Wraps produtil getstr.
def getbool (self, sec, name, default=None, badtypeok=False, morevars=None, taskvars=None)
Wraps produtil getbool.
def getint (self, sec, name, default=None, badtypeok=False, morevars=None, taskvars=None)
Wraps produtil getint to gracefully report if variable is not set and no default value is specified.
def getfloat (self, sec, name, default=None, badtypeok=False, morevars=None, taskvars=None)
Wraps produtil getint to gracefully report if variable is not set and no default value is specified.
def getseconds (self, sec, name, default=None, badtypeok=False, morevars=None, taskvars=None)
Converts time values ending in H, M, or S to seconds.
Public Attributes
logger
env
Static Public Attributes
list OLD_SECTIONS
Constructor & Destructor Documentation
__init__()
def metplus.util.config_metplus.METplusConfig.__init__ (self, conf = None)
Creates a new METplusConfig.
Parameters
conf The configuration file.
Definition at line 578 of file config_metplus.py.
Member Function Documentation
check_default()
def metplus.util.config_metplus.METplusConfig.check_default (self, sec, name, default)
helper function for get methods, report error and raise NoOptionError if default is not set.
If default is set, set the config variable to the default value so that the value is stored in the final conf Args:
Parameters
sec section of config
name name of config variable
default value to use - if set to None, error and raise exception
Definition at line 701 of file config_metplus.py.
Referenced by metplus.util.config_metplus.METplusConfig.getbool(), metplus.util.config_metplus.METplusConfig.getdir(), metplus.util.config_metplus.METplusConfig.getfloat(), metplus.util.config_metplus.METplusConfig.getint(), metplus.util.config_metplus.METplusConfig.getseconds(), and metplus.util.config_metplus.METplusConfig.getstr().
find_section()
def metplus.util.config_metplus.METplusConfig.find_section (self, sec, opt)
Search through list of previously supported config sections to find variable requested.
This allows the removal of these sections to consider all of the variables members of the [config] section. Args:
Parameters
sec section requested - look in this section first
opt configuration variable to find
Returns
section heading name or None if not found
Definition at line 627 of file config_metplus.py.
getbool()
def metplus.util.config_metplus.METplusConfig.getbool (self, sec, name, default = None, badtypeok = False, morevars = None, taskvars = None)
Wraps produtil getbool.
Config variable is checked with a default value of None because if the config is not set and a default is specified, it will just return that value. We want to log that a default was used and set it in the config so it will show up in the final conf that is generated at the end of execution. If no default was specified in the call, the NoOptionError is raised again.
Returns
None if value is not a boolean (or yes/no), value if set, default if not set
Definition at line 808 of file config_metplus.py.
getexe()
def metplus.util.config_metplus.METplusConfig.getexe (self, exe_name)
Wraps produtil exe with checks to see if option is set and if exe actually exists.
Returns None if not found instead of exiting
Definition at line 732 of file config_metplus.py.
getfloat()
def metplus.util.config_metplus.METplusConfig.getfloat (self, sec, name, default = None, badtypeok = False, morevars = None, taskvars = None)
Wraps produtil getint to gracefully report if variable is not set and no default value is specified.
Returns
Value if set, default of missing value if not set, None if value is an incorrect type
Definition at line 868 of file config_metplus.py.
getint()
def metplus.util.config_metplus.METplusConfig.getint (self, sec, name, default = None, badtypeok = False, morevars = None, taskvars = None)
Wraps produtil getint to gracefully report if variable is not set and no default value is specified.
Returns
Value if set, default of missing value if not set, None if value is an incorrect type
Definition at line 838 of file config_metplus.py.
getraw()
def metplus.util.config_metplus.METplusConfig.getraw (self, sec, opt, default = '', count = 0)
parse parameter and replace any existing parameters
    referenced with the value (looking in same section, then
    config, dir, and os environment)
    returns raw string, preserving {valid?fmt=%Y} blocks
    Args:
@param sec: Section in the conf file to look for variable
@param opt: Variable to interpret
@param default: Default value to use if config is not set
@param count: Counter used to stop recursion to prevent infinite
    Returns:
Raw string or empty string if function calls itself too many times
Definition at line 651 of file config_metplus.py.
Referenced by metplus.util.config_metplus.METplusConfig.getraw(), and metplus.util.config_metplus.METplusConfig.move_all_to_config_section().
getstr()
def metplus.util.config_metplus.METplusConfig.getstr (self, sec, name, default = None, badtypeok = False, morevars = None, taskvars = None)
Wraps produtil getstr.
Config variable is checked with a default value of None because if the config is not set and a default is specified, it will just return that value. We want to log that a default was used and set it in the config so it will show up in the final conf that is generated at the end of execution. If no default was specified in the call, the NoOptionError is raised again. Replace double forward slash with single to prevent error that occurs if that is found inside a MET config file (because it considers // the start of a comment
Definition at line 787 of file config_metplus.py.
Referenced by metplus.util.config_metplus.METplusConfig.getbool(), metplus.util.config_metplus.METplusConfig.getdir(), metplus.util.config_metplus.METplusConfig.getexe(), metplus.util.config_metplus.METplusConfig.getfloat(), metplus.util.config_metplus.METplusConfig.getint(), and metplus.util.config_metplus.METplusConfig.getseconds().
log()
def metplus.util.config_metplus.METplusConfig.log (self, sublog = None)
Overrides method in ProdConfig If the sublog argument is provided, then the logger will be under that subdomain of the "metplus" logging domain.
Otherwise, this METplusConfig's logger (usually the "metplus" domain) is returned.
Parameters
sublog the logging subdomain, or None
Returns
a logging.Logger object
Definition at line 597 of file config_metplus.py.
Member Data Documentation
OLD_SECTIONS
list metplus.util.config_metplus.METplusConfig.OLD_SECTIONS static
Initial value:
=  ['dir',
                    'exe',
                    'filename_templates',
                    'regex_pattern',
                    ]
Definition at line 572 of file config_metplus.py.
Referenced by metplus.util.config_metplus.METplusConfig.find_section(), metplus.util.config_metplus.METplusConfig.getbool(), metplus.util.config_metplus.METplusConfig.getdir(), metplus.util.config_metplus.METplusConfig.getfloat(), metplus.util.config_metplus.METplusConfig.getint(), metplus.util.config_metplus.METplusConfig.getraw(), metplus.util.config_metplus.METplusConfig.getseconds(), metplus.util.config_metplus.METplusConfig.getstr(), and metplus.util.config_metplus.METplusConfig.move_all_to_config_section().
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/METplus/metplus/util/config_metplus.py