METplus: metplus.wrappers.tc_stat_wrapper.TCStatWrapper Class Reference
metplus.wrappers.tc_stat_wrapper.TCStatWrapper Class Reference
Wrapper for the MET tool, tc_stat, which is used to filter tropical cyclone pair data.
Detailed Description
Wrapper for the MET tool, tc_stat, which is used to filter tropical cyclone pair data.
Definition at line 34 of file tc_stat_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def create_c_dict (self)
Read in and store all the values from the config file.
def set_met_config_for_environment_variables (self, c_dict)
Set c_dict dictionary entries that will be set as environment variables to be read by the MET config file.
def run_at_time (self, input_dict=None)
Builds the call to the MET tool TC-STAT for all requested initialization times (init or valid).
def get_command (self)
Builds the command to run the MET application string.
def set_environment_variables (self, time_info)
Set the env variables based on settings in the METplus config files.
def handle_jobs (self, time_info)
Loop through job list found in c_dict key JOBS, create parent directory for -dump_row path if it is set, and format jobs string to pass to MET config file.
def validate_config_values (self, c_dict)
Verify that the length of the name and val lists in the MET tc-stat config file are of equal length, if not, log an error message and exit.
Public Attributes
app_name
app_path
Member Function Documentation
create_c_dict()
def metplus.wrappers.tc_stat_wrapper.TCStatWrapper.create_c_dict (self)
Read in and store all the values from the config file.
This will make it easier to reassign values while unit testing and make it easier when retrieving these values, especially when they are needed multiple times by different methods.
Returns
a dictionary of the key-value representation of options set in the config file.
Definition at line 49 of file tc_stat_wrapper.py.
get_command()
def metplus.wrappers.tc_stat_wrapper.TCStatWrapper.get_command (self)
Builds the command to run the MET application string.
Returns
Returns a MET command with arguments that you can run
Definition at line 189 of file tc_stat_wrapper.py.
Referenced by metplus.wrappers.tcmpr_plotter_wrapper.TCMPRPlotterWrapper.build(), and metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once().
handle_jobs()
def metplus.wrappers.tc_stat_wrapper.TCStatWrapper.handle_jobs (self, time_info)
Loop through job list found in c_dict key JOBS, create parent directory for -dump_row path if it is set, and format jobs string to pass to MET config file.
Parameters
time_info time dictionary used to fill in filename template tags if used
Returns
formatted jobs string as jobs = ["job1", "job2"]; or None if command should be skipped
Definition at line 269 of file tc_stat_wrapper.py.
Referenced by metplus.wrappers.tc_stat_wrapper.TCStatWrapper.set_environment_variables().
run_at_time()
def metplus.wrappers.tc_stat_wrapper.TCStatWrapper.run_at_time (self, input_dict = None)
Builds the call to the MET tool TC-STAT for all requested initialization times (init or valid).
Called from master_metplus
Definition at line 174 of file tc_stat_wrapper.py.
set_environment_variables()
def metplus.wrappers.tc_stat_wrapper.TCStatWrapper.set_environment_variables (self, time_info)
Set the env variables based on settings in the METplus config files.
Parameters
time_info dictionary containing time information
Returns
True if command should be run, False if skipping
Definition at line 203 of file tc_stat_wrapper.py.
Referenced by metplus.wrappers.make_plots_wrapper.MakePlotsWrapper.create_c_dict(), metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation(), metplus.wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper.run_at_time(), metplus.wrappers.tc_stat_wrapper.TCStatWrapper.run_at_time(), metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), metplus.wrappers.user_script_wrapper.UserScriptWrapper.run_at_time_once(), metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time_once(), metplus.wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once(), and metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
set_met_config_for_environment_variables()
def metplus.wrappers.tc_stat_wrapper.TCStatWrapper.set_met_config_for_environment_variables (self, c_dict)
Set c_dict dictionary entries that will be set as environment variables to be read by the MET config file.
Parameters
c_dict dictionary to add key/value pairs
Definition at line 99 of file tc_stat_wrapper.py.
Referenced by metplus.wrappers.tc_stat_wrapper.TCStatWrapper.create_c_dict().
validate_config_values()
def metplus.wrappers.tc_stat_wrapper.TCStatWrapper.validate_config_values (self, c_dict)
Verify that the length of the name and val lists in the MET tc-stat config file are of equal length, if not, log an error message and exit.
As soon as a length mismatch is encountered, return False.
Args:
Returns: True: if all corresponding <>_NAME and <>_VAL lists have the same length False: if any name/val list length mismatch is encountered
Definition at line 300 of file tc_stat_wrapper.py.
Referenced by metplus.wrappers.tc_stat_wrapper.TCStatWrapper.set_met_config_for_environment_variables().
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/METplus/metplus/wrappers/tc_stat_wrapper.py