METplus: metplus.wrappers.mode_wrapper.MODEWrapper Class Reference
metplus.wrappers.mode_wrapper.MODEWrapper Class Reference
Wrapper for the mode MET tool.
Detailed Description
Wrapper for the mode MET tool.
Definition at line 19 of file mode_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def add_merge_config_file (self, time_info)
If merge config file is defined, add it to the command.
def create_c_dict (self)
def set_environment_variables (self, fcst_field, obs_field, time_info)
def run_at_time_one_field (self, time_info, var_info)
Runs mode instances for a given time and forecast lead combination Overrides run_at_time_one_field function in compare_gridded_wrapper.py Args:
def process_fields_one_thresh (self, time_info, var_info, model_path, obs_path)
For each threshold, set up environment variables and run mode Args:
Public Attributes
app_name
app_path
isOK
param
Member Function Documentation
process_fields_one_thresh()
def metplus.wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh (self, time_info, var_info, model_path, obs_path)
For each threshold, set up environment variables and run mode Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
model_path forecast file
obs_path observation file
Definition at line 190 of file mode_wrapper.py.
Referenced by metplus.wrappers.mtd_wrapper.MTDWrapper.run_at_time_loop_string(), and metplus.wrappers.mode_wrapper.MODEWrapper.run_at_time_one_field().
run_at_time_one_field()
def metplus.wrappers.mode_wrapper.MODEWrapper.run_at_time_one_field (self, time_info, var_info)
Runs mode instances for a given time and forecast lead combination Overrides run_at_time_one_field function in compare_gridded_wrapper.py Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
Definition at line 169 of file mode_wrapper.py.
Referenced by metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/METplus/metplus/wrappers/mode_wrapper.py