METplus: metplus.util.string_template_substitution Namespace Reference
metplus.util.string_template_substitution Namespace Reference
Detailed Description
Program Name: string_template_substitution.py
Contact(s): Julie Prestopnik, NCAR RAL DTC, jpresto@ucar.edu, George McCabe
Abstract: Supporting functions for parsing and creating filename templates
History Log:  Initial version for METPlus
Usage: Usually imported in other Python code for individual function calls
Parameters: Varies
Input Files: None
Output Files: None
Condition codes: Varies
Functions
def multiple_replace (replace_dict, text)
def get_tags (template)
Parse template and pull out all wildcard characters (* or ?) and all tags, i.e.
def format_one_time_item (item, time_str, unit)
Helper function for do_string_sub.
def format_hms (fmt, obj)
Helper function for do_string_sub.
def set_output_dict_from_time_info (time_dict, output_dict, key)
Create datetime object from time data, get month and day from julian date if applicable.
def add_to_dict (match, match_dict, filepath, new_len)
Add extracted information to match dictionary Args:
def get_seconds_from_template (split_string, element_name, kwargs)
Get seconds value from tag that contains a shift or truncate item Args:
def round_time_down (obj, truncate_seconds)
If template value needs to be truncated, round the value down to the given truncate interval.
def handle_format_delimiter (split_string, idx, shift_seconds, truncate_seconds, kwargs)
Check for formatting/length request by splitting on FORMATTING_VALUE_DELIMITER split_string[1] Args:
def do_string_sub (tmpl, skip_missing_tags=False, kwargs)
def find_and_replace_tags_in_template (match_list, tmpl, kwargs, skip_missing_tags=False)
Loop through tags from template and replace them with the correct time values.
def parse_template (template, filepath, logger=None)
Extract time information from path using the filename template Args:
def populate_match_dict (template, filepath, logger=None)
Use template to extract time information from filepath, add each value to a dictionary.
def process_match_tags (all_tags, filepath, logger)
Loop through tags and process each.
def check_pre_text (filepath, pre_text, logger=None)
Check if there is an text before all tags and if they match the template.
def check_post_text (filepath, post_text, logger=None)
Check if there is an text after all tags and if they match the template.
def get_format_and_shift (tag_content, filepath, match_dict, valid_shift, extra_text)
Extract format and shift information from tag.
def get_fmt_info (fmt, filepath, match_dict, identifier)
Helper function for parse_template.
def populate_output_dict (match_dict, valid_shift)
Get all time values in match dictionary to add to the output dictionary Args:
def add_date_matches_to_output_dict (match_dict, output_dict, time_type, valid_shift=0)
Look for time values in match dictionary add combine the values to add to the output dictionary.
def add_lead_matches_to_output_dict (match_dict, output_dict)
Look for forecast lead values in match dictionary add combine the values to add to the output dictionary Args:
def add_offset_matches_to_output_dict (match_dict, output_dict)
Look for offset value in match dictionary and add the value to the output dictionary Args:
def extract_lead (template, filename)
Variables
string TEMPLATE_IDENTIFIER_BEGIN = "{"
string TEMPLATE_IDENTIFIER_END = "}"
string FORMATTING_DELIMITER = "?"
string FORMATTING_VALUE_DELIMITER = "="
string FORMAT_STRING = "fmt"
string SHIFT_STRING = "shift"
string TRUNCATE_STRING = "truncate"
string VALID_STRING = "valid"
string LEAD_STRING = "lead"
string INIT_STRING = "init"
string DA_INIT_STRING = "da_init"
string OFFSET_STRING = "offset"
dictionary LENGTH_DICT
Function Documentation
add_date_matches_to_output_dict()
def metplus.util.string_template_substitution.add_date_matches_to_output_dict (match_dict, output_dict, time_type, valid_shift = 0)
Look for time values in match dictionary add combine the values to add to the output dictionary.
Apply shift value for valid time only. Args:
Parameters
match_dict dictionary containing matches found with keys named 'valid+Y','init+m', 'da_init+d', etc. and values are the number of years, months, hours, etc.
output_dict time dictionary to set valid, init, or da_init
time_type type of time item to process. Valid options are: VALID_STRING, INIT_STRING, or DA_INIT_STRING
valid_shift amount of time (in seconds) to shift the valid time Not applicable for any time type besides valid
Definition at line 791 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.populate_output_dict().
add_lead_matches_to_output_dict()
def metplus.util.string_template_substitution.add_lead_matches_to_output_dict (match_dict, output_dict)
Look for forecast lead values in match dictionary add combine the values to add to the output dictionary Args:
Parameters
match_dict dictionary containing matches found with keys named 'lead+H','lead+M', or 'lead+S' and values are the number of hours, minutes, or seconds in the forecast lead
output_dict time dictionary to set lead
Definition at line 825 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.populate_output_dict().
add_offset_matches_to_output_dict()
def metplus.util.string_template_substitution.add_offset_matches_to_output_dict (match_dict, output_dict)
Look for offset value in match dictionary and add the value to the output dictionary Args:
Parameters
match_dict dictionary containing matches found with keys named 'offset+H' (only hours are supported for offset) and value is number of hours in the offset
output_dict time dictionary to set offset_hours
Definition at line 847 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.populate_output_dict().
add_to_dict()
def metplus.util.string_template_substitution.add_to_dict (match, match_dict, filepath, new_len)
Add extracted information to match dictionary Args:
Parameters
match key for match dictionary containing tag name and units i.e. 'init+H' or 'lead+S'
match_dict dictionary of info extracted from filename
filepath rest of filename string to be parsed
new_len length of filepath to extract Returns: True if info was added to dictionary or it already exists and matched newly parsed info, False if info could not be extracted or if info differed from info already in match dictionary
Definition at line 179 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.get_fmt_info().
check_post_text()
def metplus.util.string_template_substitution.check_post_text (filepath, post_text, logger = None)
Check if there is an text after all tags and if they match the template.
Strip off text from filepath.
Parameters
filepath path to check
post_text text after all tags
Returns
file path with post text removed or None if text does not match template
Definition at line 607 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.populate_match_dict().
check_pre_text()
def metplus.util.string_template_substitution.check_pre_text (filepath, pre_text, logger = None)
Check if there is an text before all tags and if they match the template.
Strip off text from filepath.
Parameters
filepath path to check
pre_text text before any tags
post_text text after all tags
Returns
file path with pre text removed or None if text does not match template
Definition at line 575 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.populate_match_dict(), and metplus.util.string_template_substitution.process_match_tags().
do_string_sub()
def metplus.util.string_template_substitution.do_string_sub (tmpl, skip_missing_tags = False, kwargs)
log - log object
tmpl_str - template string to populate
kwargs - dictionary containing values for each template key
This class provides functionality for substituting values for
string templates.
Possible keys for vals:
   init - datetime object
   valid - datetime object
   lead - must be in seconds
   level - must be in seconds
   model - the name of the model
   domain - the domain number (01, 02, etc.) read in as a string
   cycle - the cycle hour in HH format (00, 03, 06, etc.)
   offset_hour - the offset hour in HH format to add
                 to the init + cycl time:
                  (YYYYMMDD + hh) + offset
                 Indicate a negative offset by using a '-' sign
                 in the
   date - datetime object
   region - the two-character (upper or lower case) region/basin designation
   cyclone - a two-digit annual cyclone number (if ATCF_by_pairs) or
             four-digit cyclone number (leading zeros)
   misc - any string
Populates the specified template with information from the
       kwargs dictionary.  The template structure is comprised of
       a fixed string populated with template place-holders inside curly
       braces, for example {tmpl_str}.  The tmpl_str must be present as
       a key in the kwargs dictionary, and the value will replace the
       {tmpl_str} in the returned string.
        In some cases, the template keys can have parameters containing
        formatting information. The format of the template in this case
        is {tmpl_str?parm=val}.  The supported parameters are:
        init, valid:
            fmt - specifies a strftime format for the date/time
                  e.g. %Y%m%d%H%M%S, %Y%m%d%H
          lead, level:
            fmt -  specifies an amount of time in [H]HH[MMSS] format
                   e.g. %HH, %HHH, %HH%MMSS, %HHH%MMSS
          cycle, negative_offset, positive_offset:
            fmt - specifies the cycle and offset hours in HH format. H and
                  HHH format are supported, to anticipate any changes
                  in prepbufr data.
          The following were created to support processing of
          tropical cyclone data:
          cyclone:
            fmt - specifies the annual cyclone number as a string.
          region:
            fmt - a string that specifies the region/basin of cyclone.
                  For ATCF_by_pairs formatted data, this is a 2-character
                  designation:
                  AL|WP|CP|EP|SH|IO|LS lower case designations are
                  observed in filenames.
          date:
            fmt - a string representation of the date format for a
                  subdirectory in which track data resides, or the
                  string representation of the date format in a file.
                  Expected formats: YYYY, YYYYMM, YYYYMMDD, and YYYYMMDDhh
          misc:
            fmt -a string that represents any other miscellaneous feature
                 of the track data, such as experiment name or some other descriptor
Definition at line 298 of file string_template_substitution.py.
find_and_replace_tags_in_template()
def metplus.util.string_template_substitution.find_and_replace_tags_in_template (match_list, tmpl, kwargs, skip_missing_tags = False)
Loop through tags from template and replace them with the correct time values.
Parameters
match_list list of tags to process
template filename template to substitute values into
kwargs all
Definition at line 401 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.do_string_sub().
format_hms()
def metplus.util.string_template_substitution.format_hms (fmt, obj)
Helper function for do_string_sub.
For time offset values, get hour, minute, and second values to format as necessary Args:
Parameters
fmt format to substitute, i.e. %3H or %2M or S
obj time value in seconds to format, i.e. 3600 Returns: Formatted time value
Definition at line 112 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.handle_format_delimiter().
format_one_time_item()
def metplus.util.string_template_substitution.format_one_time_item (item, time_str, unit)
Helper function for do_string_sub.
Determine precision of time offset value and format Args:
Parameters
item format to substitute, i.e. 3M or H
time_str time value that precision will be applied, i.e. 60
unit currently being processed, i.e. M or H or S Returns: Padded value or empty string if unit is not found in item
Definition at line 82 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.format_hms().
get_fmt_info()
def metplus.util.string_template_substitution.get_fmt_info (fmt, filepath, match_dict, identifier)
Helper function for parse_template.
Reads format information from tag and populates dictionary with extracted values. Args:
Parameters
fmt formatting values from template tag, i.e. Ymd
filepath rest of text from filename that can be parsed
match_dict dictionary of extracted information. Key is made up of the identifier and the format tag, i.e. init_H or valid_M. Value is the extracted information, i.e. 19870201
identifier tag name, i.e. 'init' or 'lead'
Returns
Number of characters processed from the filename if success, -1 if failed to parse all format items in template tag
Definition at line 685 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.get_format_and_shift().
get_format_and_shift()
def metplus.util.string_template_substitution.get_format_and_shift (tag_content, filepath, match_dict, valid_shift, extra_text)
Extract format and shift information from tag.
Raises TypeError if shift keyword is applied to a tag other than valid or if 2 different shift values are found Args:
Parameters
tag_content text inside a tag, i.e. valid?fmt=Ymd?shift=30
filepath rest of filepath to process, i.e. 20190201.ext
match_dict dictionary to add time info
valid_shift current numbers of seconds to shift valid time
Returns
tuple of the length of the formatted time info (i.e. 8 for Ymd) and valid shift value
Definition at line 630 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.process_match_tags().
get_seconds_from_template()
def metplus.util.string_template_substitution.get_seconds_from_template (split_string, element_name, kwargs)
Get seconds value from tag that contains a shift or truncate item Args:
Parameters
split_string list of key/value from string sub tag to evalute, i.e. shift=-1H
element_name information to extract, i.e. shift or truncate
Returns
integer number of seconds that correspond to the item, i.e. -3600
Definition at line 206 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.find_and_replace_tags_in_template().
get_tags()
def metplus.util.string_template_substitution.get_tags (template)
Parse template and pull out all wildcard characters (* or ?) and all tags, i.e.
{init?fmt=H}. Used to pull out information from a template that contains wildcards and add that information when filled out another template Returns a list of wildcards and tag names found, i.e. [ '*', 'init', 'lead']
Definition at line 59 of file string_template_substitution.py.
handle_format_delimiter()
def metplus.util.string_template_substitution.handle_format_delimiter (split_string, idx, shift_seconds, truncate_seconds, kwargs)
Check for formatting/length request by splitting on FORMATTING_VALUE_DELIMITER split_string[1] Args:
Parameters
split_string holds the formatting/length information (e.g. "fmt=%Y%m%d", "len=3")
idx index in split_string of the format item Returns: Formatted string
Definition at line 247 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.find_and_replace_tags_in_template().
multiple_replace()
def metplus.util.string_template_substitution.multiple_replace (replace_dict, text)
Helper function for do_string_sub. Replace in 'text' all occurrences of any key in the
given dictionary by its corresponding value.  Returns the new string.
Definition at line 49 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.find_and_replace_tags_in_template().
parse_template()
def metplus.util.string_template_substitution.parse_template (template, filepath, logger = None)
Extract time information from path using the filename template Args:
Parameters
template filename template to use to extract time information
filepath path to examine
Returns
time_info dictionary with time information if successful, None if not
Definition at line 467 of file string_template_substitution.py.
populate_match_dict()
def metplus.util.string_template_substitution.populate_match_dict (template, filepath, logger = None)
Use template to extract time information from filepath, add each value to a dictionary.
Populates a dictionary with keys that contain tag name + time type, i.e. init+Y, valid+M, or lead+S, with string values containing the number extracted from the filepath. Also determines the shift amount for valid time if it was found, i.e. {valid?fmt=Ymd?shift=-30}. Valid shift will be 0 if no shift. Note: valid time values will not have the shift applied. Args:
Parameters
template filename template to use to find time information, i.e. file.{valid?fmt=Ymd}.ext
filepath path to examine, i.e. file.20190201.ext
Returns
tuple of match dictionary and valid shift value if success, i.e. ({'init+Y': '2019'}, -30) Returns (None, None) if could not extract time info
Definition at line 494 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.parse_template().
populate_output_dict()
def metplus.util.string_template_substitution.populate_output_dict (match_dict, valid_shift)
Get all time values in match dictionary to add to the output dictionary Args:
Parameters
match_dict dictionary containing matches found with keys named
valid_shift number of seconds to shift the valid time
Returns
output dictionary containing the extracted time information
Definition at line 761 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.parse_template().
process_match_tags()
def metplus.util.string_template_substitution.process_match_tags (all_tags, filepath, logger)
Loop through tags and process each.
Parameters
all_tags string containing all tags with non-tag text removed from beginning and end.
filepath path to process
logger optional logger to output error information
Returns
tuple containing dictionary with match information and valid shift value if applicable, or (None, None) could not parse information
Definition at line 527 of file string_template_substitution.py.
Referenced by metplus.util.string_template_substitution.populate_match_dict().
Variable Documentation
LENGTH_DICT
dictionary metplus.util.string_template_substitution.LENGTH_DICT
Initial value:
 =  {'Y': 4,
                'm': 2,
                'd': 2,
                'H': 2,
                'M': 2,
                'S': 2,
                'j': 3,
                'y': 2,
                'b': 3,
                }
Definition at line 37 of file string_template_substitution.py.