METplus: metplus.util.metplus_check Namespace Reference
metplus.util.metplus_check Namespace Reference
Detailed Description
Check that user's environment is set up correctly to run METplus wrappers
- check that the version of python is >= to the currently supported version
- check environment variables for conflicts
Functions
def metplus_check_python_version (user_py, supported_py)
Test that the user's version of python is equal of higher than the the supported version of python.
def metplus_check_environment_variables (environ)
Check environment variables that are set and ensure there aren't any conflicts.
def evaluates_to_true (value)
Check if the value matches an expression that should be interpretted as False Without this, environment variables that are set are interpretted as True no matter what value they hold.
def plot_wrappers_are_enabled (environ)
Check METPLUS_[DISABLE/ENABLE]_PLOT_WRAPPERS.
Variables
string SUPPORTED_PY_VERSION = '3.6.3'
USER_PY_VERSION = sys.version.split(' ')[0]
def compatible_python_version
def compatible_environment = metplus_check_environment_variables(os.environ)
Function Documentation
evaluates_to_true()
def metplus.util.metplus_check.evaluates_to_true (value)
Check if the value matches an expression that should be interpretted as False Without this, environment variables that are set are interpretted as True no matter what value they hold.
This checks against common expressions like false, no, off, and 0. This was leveraged from the get_bool logic in produtil config. If the value does not match the False expressions, it is considered to be True no matter what the value contains, i.e. mud Args:
Parameters
value value to check
Returns
False if value matches a supported False expression, True otherwise
Definition at line 55 of file metplus_check.py.
Referenced by metplus.util.metplus_check.plot_wrappers_are_enabled().
metplus_check_environment_variables()
def metplus.util.metplus_check.metplus_check_environment_variables (environ)
Check environment variables that are set and ensure there aren't any conflicts.
Parameters
environ dictionary containing environment variables that are set
Returns
True if environment is OK to run METplus wrappers, False if not
Definition at line 44 of file metplus_check.py.
Referenced by metplus.util.metplus_check.plot_wrappers_are_enabled().
metplus_check_python_version()
def metplus.util.metplus_check.metplus_check_python_version (user_py, supported_py)
Test that the user's version of python is equal of higher than the the supported version of python.
Imported in each wrapper and master_metplus to avoid confusing failures if the user's version is not current. Note: SyntaxError from using f-strings (available in 3.6+) in earlier versions of Python are output before the output from this function can be displayed. Args:
Parameters
user_py user's python version number, i.e. 3.8.1
supported_py currently supported python version number, i.e. 3.6.3
Returns
True if version is at least supported, False if not
Definition at line 12 of file metplus_check.py.
Referenced by metplus.util.metplus_check.plot_wrappers_are_enabled().
plot_wrappers_are_enabled()
def metplus.util.metplus_check.plot_wrappers_are_enabled (environ)
Check METPLUS_[DISABLE/ENABLE]_PLOT_WRAPPERS.
If both are set it should error and exit. Otherwise it should warn if DISABLE if used beacuse ENABLE should be used instead.
Parameters
environ dictionary containing environment variables that are set
Returns
True if plot wrappers are enabled, False if they are disabled, and None if both environment variables are set, which is not allowed
Definition at line 71 of file metplus_check.py.
Referenced by metplus.util.metplus_check.metplus_check_environment_variables().
Variable Documentation
compatible_python_version
def metplus.util.metplus_check.compatible_python_version
Initial value:
 =  metplus_check_python_version(USER_PY_VERSION,
                                                          SUPPORTED_PY_VERSION)
Definition at line 101 of file metplus_check.py.