METplus: metplus.util.time_util Namespace Reference
metplus.util.time_util Namespace Reference
Detailed Description
Program Name: time_util.py
Contact(s): George McCabe
Abstract:
History Log:  Initial version
Usage: Create a subclass
Parameters: None
Input Files: N/A
Output Files: N/A
Functions
def get_relativedelta (value, default_unit='S')
Converts time values ending in Y, m, d, H, M, or S to relativedelta object Args:
def get_seconds_from_string (value, default_unit='S', valid_time=None)
Convert string of time (optionally ending with time letter, i.e.
def time_string_to_met_time (time_string, default_unit='S')
Convert time string (3H, 4M, 7, etc.) to format expected by the MET tools ([H]HH[MM[SS]])
def seconds_to_met_time (total_seconds)
def ti_get_hours_from_relativedelta (lead, valid_time=None)
Get hours from relativedelta.
def ti_get_seconds_from_relativedelta (lead, valid_time=None)
Check relativedelta object contents and compute the total number of seconds in the time.
def ti_get_seconds_from_lead (lead, valid=' *')
def ti_get_hours_from_lead (lead, valid=' *')
def get_time_suffix (letter, letter_only)
def format_time_string (lead, letter, plural, letter_only)
def ti_get_lead_string (lead, plural=True, letter_only=False)
Check relativedelta object contents and create string representation of the highest unit available (year, then, month, day, hour, minute, second).
def ti_calculate (input_dict_preserve)
Variables
dictionary TIME_LETTER_TO_STRING
Function Documentation
get_relativedelta()
def metplus.util.time_util.get_relativedelta (value, default_unit = 'S')
Converts time values ending in Y, m, d, H, M, or S to relativedelta object Args:
Parameters
value time value optionally ending in Y,m,d,H,M,S Valid options match format 3600, 3600S, 60M, or 1H
default_unit unit to assume if no letter is found at end of value
Returns
relativedelta object containing offset time
Definition at line 35 of file time_util.py.
Referenced by metplus.util.time_util.get_seconds_from_string().
get_seconds_from_string()
def metplus.util.time_util.get_seconds_from_string (value, default_unit = 'S', valid_time = None)
Convert string of time (optionally ending with time letter, i.e.
HMSyMD to seconds Args:
Parameters
value string to convert, i.e. 3M, 4H, 17
default_unit units to apply if not specified at end of string
Returns
time in seconds if successfully parsed, None if not
Definition at line 83 of file time_util.py.
Referenced by metplus.util.time_util.time_string_to_met_time().
ti_get_hours_from_relativedelta()
def metplus.util.time_util.ti_get_hours_from_relativedelta (lead, valid_time = None)
Get hours from relativedelta.
Simply calls get seconds function and divides the result by 3600.
Parameters
lead relativedelta object to convert
valid_time (optional) valid time required to convert values that contain months or years
Returns
integer value of hours or None if cannot compute
Definition at line 111 of file time_util.py.
ti_get_lead_string()
def metplus.util.time_util.ti_get_lead_string (lead, plural = True, letter_only = False)
Check relativedelta object contents and create string representation of the highest unit available (year, then, month, day, hour, minute, second).
This assumes that only one unit has been set in the object
Definition at line 214 of file time_util.py.
ti_get_seconds_from_relativedelta()
def metplus.util.time_util.ti_get_seconds_from_relativedelta (lead, valid_time = None)
Check relativedelta object contents and compute the total number of seconds in the time.
Return None if years or months are set, because the exact number of seconds cannot be calculated without a relative time
Definition at line 131 of file time_util.py.
Referenced by metplus.util.time_util.get_seconds_from_string(), and metplus.util.time_util.ti_get_hours_from_relativedelta().
Variable Documentation
TIME_LETTER_TO_STRING
dictionary metplus.util.time_util.TIME_LETTER_TO_STRING
Initial value:
 =  {
     'Y': 'year',
     'm': 'month',
     'd': 'day',
     'H': 'hour',
     'M': 'minute',
     'S': 'second',
 }
Definition at line 26 of file time_util.py.